
/*
	File generated by NetTiers templates [www.nettiers.com]
	Important: Do not modify this file. Edit the file CourseGroup.cs instead.
*/

#region using directives
using System;
using System.ComponentModel;
using System.Collections;
using System.Xml.Serialization;
using System.Runtime.Serialization;

using AIProject.Entities.Validation;
#endregion

namespace AIProject.Entities
{
	///<summary>
	/// An object representation of the 'CourseGroup' table. [No description found the database]	
	///</summary>
	[Serializable]
	[DataObject, CLSCompliant(true)]
	public abstract partial class CourseGroupBase : EntityBase, ICourseGroup, IEntityId<CourseGroupKey>, System.IComparable, System.ICloneable, ICloneableEx, IEditableObject, IComponent, INotifyPropertyChanged
	{		
		#region Variable Declarations
		
		/// <summary>
		///  Hold the inner data of the entity.
		/// </summary>
		private CourseGroupEntityData entityData;
		
		/// <summary>
		/// 	Hold the original data of the entity, as loaded from the repository.
		/// </summary>
		private CourseGroupEntityData _originalData;
		
		/// <summary>
		/// 	Hold a backup of the inner data of the entity.
		/// </summary>
		private CourseGroupEntityData backupData; 
		
		/// <summary>
		/// 	Key used if Tracking is Enabled for the <see cref="EntityLocator" />.
		/// </summary>
		private string entityTrackingKey;
		
		/// <summary>
		/// 	Hold the parent TList&lt;entity&gt; in which this entity maybe contained.
		/// </summary>
		/// <remark>Mostly used for databinding</remark>
		[NonSerialized]
		private TList<CourseGroup> parentCollection;
		
		private bool inTxn = false;
		
		/// <summary>
		/// Occurs when a value is being changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event CourseGroupEventHandler ColumnChanging;		
		
		/// <summary>
		/// Occurs after a value has been changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event CourseGroupEventHandler ColumnChanged;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="CourseGroupBase"/> instance.
		///</summary>
		public CourseGroupBase()
		{
			this.entityData = new CourseGroupEntityData();
			this.backupData = null;
		}		
		
		///<summary>
		/// Creates a new <see cref="CourseGroupBase"/> instance.
		///</summary>
		///<param name="_courseGroupId"></param>
		///<param name="_name"></param>
		///<param name="_note"></param>
		public CourseGroupBase(System.Int32 _courseGroupId, System.String _name, System.String _note)
		{
			this.entityData = new CourseGroupEntityData();
			this.backupData = null;

			this.CourseGroupId = _courseGroupId;
			this.Name = _name;
			this.Note = _note;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="CourseGroup"/> instance.
		///</summary>
		///<param name="_courseGroupId"></param>
		///<param name="_name"></param>
		///<param name="_note"></param>
		public static CourseGroup CreateCourseGroup(System.Int32 _courseGroupId, System.String _name, System.String _note)
		{
			CourseGroup newCourseGroup = new CourseGroup();
			newCourseGroup.CourseGroupId = _courseGroupId;
			newCourseGroup.Name = _name;
			newCourseGroup.Note = _note;
			return newCourseGroup;
		}
				
		#endregion Constructors
			
		#region Properties	
		
		#region Data Properties		
		/// <summary>
		/// 	Gets or sets the CourseGroupId property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, false, false)]
		public virtual System.Int32 CourseGroupId
		{
			get
			{
				return this.entityData.CourseGroupId; 
			}
			
			set
			{
				if (this.entityData.CourseGroupId == value)
					return;
					
				OnColumnChanging(CourseGroupColumn.CourseGroupId, this.entityData.CourseGroupId);
				this.entityData.CourseGroupId = value;
				this.EntityId.CourseGroupId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(CourseGroupColumn.CourseGroupId, this.entityData.CourseGroupId);
				OnPropertyChanged("CourseGroupId");
			}
		}
		
		/// <summary>
		/// 	Get the original value of the CourseGroupId property.
		///		
		/// </summary>
		/// <remarks>This is the original value of the CourseGroupId property.</remarks>
		/// <value>This type is int</value>
		[BrowsableAttribute(false)/*, XmlIgnoreAttribute()*/]
		public  virtual System.Int32 OriginalCourseGroupId
		{
			get { return this.entityData.OriginalCourseGroupId; }
			set { this.entityData.OriginalCourseGroupId = value; }
		}
		
		/// <summary>
		/// 	Gets or sets the Name property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 50)]
		public virtual System.String Name
		{
			get
			{
				return this.entityData.Name; 
			}
			
			set
			{
				if (this.entityData.Name == value)
					return;
					
				OnColumnChanging(CourseGroupColumn.Name, this.entityData.Name);
				this.entityData.Name = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(CourseGroupColumn.Name, this.entityData.Name);
				OnPropertyChanged("Name");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Note property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 1024)]
		public virtual System.String Note
		{
			get
			{
				return this.entityData.Note; 
			}
			
			set
			{
				if (this.entityData.Note == value)
					return;
					
				OnColumnChanging(CourseGroupColumn.Note, this.entityData.Note);
				this.entityData.Note = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(CourseGroupColumn.Note, this.entityData.Note);
				OnPropertyChanged("Note");
			}
		}
		
		#endregion Data Properties		

		#region Source Foreign Key Property
				
		#endregion
		
		#region Children Collections
	
		/// <summary>
		///	Holds a collection of CourseDetails objects
		///	which are related to this object through the relation FK_CourseDetails_CourseGroup
		/// </summary>	
		[System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual TList<CourseDetails> CourseDetailsCollection
		{
			get { return entityData.CourseDetailsCollection; }
			set { entityData.CourseDetailsCollection = value; }	
		}
		#endregion Children Collections
		
		#endregion
		#region Validation
		
		/// <summary>
		/// Assigns validation rules to this object based on model definition.
		/// </summary>
		/// <remarks>This method overrides the base class to add schema related validation.</remarks>
		protected override void AddValidationRules()
		{
			//Validation rules based on database schema.
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("Name", "Name", 50));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("Note", "Note", 1024));
		}
   		#endregion
		
		#region Table Meta Data
		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string TableName
		{
			get { return "CourseGroup"; }
		}
		
		/// <summary>
		///		The name of the underlying database table's columns.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string[] TableColumns
		{
			get
			{
				return new string[] {"CourseGroupId", "Name", "Note"};
			}
		}
		#endregion 
		
		#region IEditableObject
		
		#region  CancelAddNew Event
		/// <summary>
        /// The delegate for the CancelAddNew event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		public delegate void CancelAddNewEventHandler(object sender, EventArgs e);
    
    	/// <summary>
		/// The CancelAddNew event.
		/// </summary>
		[field:NonSerialized]
		public event CancelAddNewEventHandler CancelAddNew ;

		/// <summary>
        /// Called when [cancel add new].
        /// </summary>
        public void OnCancelAddNew()
        {    
			if (!SuppressEntityEvents)
			{
	            CancelAddNewEventHandler handler = CancelAddNew ;
            	if (handler != null)
	            {    
    	            handler(this, EventArgs.Empty) ;
        	    }
	        }
        }
		#endregion 
		
		/// <summary>
		/// Begins an edit on an object.
		/// </summary>
		void IEditableObject.BeginEdit() 
	    {
	        //Console.WriteLine("Start BeginEdit");
	        if (!inTxn) 
	        {
	            this.backupData = this.entityData.Clone() as CourseGroupEntityData;
	            inTxn = true;
	            //Console.WriteLine("BeginEdit");
	        }
	        //Console.WriteLine("End BeginEdit");
	    }
	
		/// <summary>
		/// Discards changes since the last <c>BeginEdit</c> call.
		/// </summary>
	    void IEditableObject.CancelEdit() 
	    {
	        //Console.WriteLine("Start CancelEdit");
	        if (this.inTxn) 
	        {
	            this.entityData = this.backupData;
	            this.backupData = null;
				this.inTxn = false;

				if (this.bindingIsNew)
	        	//if (this.EntityState == EntityState.Added)
	        	{
					if (this.parentCollection != null)
						this.parentCollection.Remove( (CourseGroup) this ) ;
				}	            
	        }
	        //Console.WriteLine("End CancelEdit");
	    }
	
		/// <summary>
		/// Pushes changes since the last <c>BeginEdit</c> or <c>IBindingList.AddNew</c> call into the underlying object.
		/// </summary>
	    void IEditableObject.EndEdit() 
	    {
	        //Console.WriteLine("Start EndEdit" + this.custData.id + this.custData.lastName);
	        if (this.inTxn) 
	        {
	            this.backupData = null;
				if (this.IsDirty) 
				{
					if (this.bindingIsNew) {
						this.EntityState = EntityState.Added;
						this.bindingIsNew = false ;
					}
					else
						if (this.EntityState == EntityState.Unchanged) 
							this.EntityState = EntityState.Changed ;
				}

				this.bindingIsNew = false ;
	            this.inTxn = false;	            
	        }
	        //Console.WriteLine("End EndEdit");
	    }
	    
	    /// <summary>
        /// Gets or sets the parent collection of this current entity, if available.
        /// </summary>
        /// <value>The parent collection.</value>
	    [XmlIgnore]
		[Browsable(false)]
	    public override object ParentCollection
	    {
	        get 
	        {
	            return this.parentCollection;
	        }
	        set 
	        {
	            this.parentCollection = value as TList<CourseGroup>;
	        }
	    }
	    
	    /// <summary>
        /// Called when the entity is changed.
        /// </summary>
	    private void OnEntityChanged() 
	    {
	        if (!SuppressEntityEvents && !inTxn && this.parentCollection != null) 
	        {
	            this.parentCollection.EntityChanged(this as CourseGroup);
	        }
	    }


		#endregion
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed CourseGroup Entity 
		///</summary>
		protected virtual CourseGroup Copy(IDictionary existingCopies)
		{
			if (existingCopies == null)
			{
				// This is the root of the tree to be copied!
				existingCopies = new Hashtable();
			}

			//shallow copy entity
			CourseGroup copy = new CourseGroup();
			existingCopies.Add(this, copy);
			copy.SuppressEntityEvents = true;
				copy.CourseGroupId = this.CourseGroupId;
					copy.OriginalCourseGroupId = this.OriginalCourseGroupId;
				copy.Name = this.Name;
				copy.Note = this.Note;
			
		
			//deep copy nested objects
			copy.CourseDetailsCollection = (TList<CourseDetails>) MakeCopyOf(this.CourseDetailsCollection, existingCopies); 
			copy.EntityState = this.EntityState;
			copy.SuppressEntityEvents = false;
			return copy;
		}		
		
		
		
		///<summary>
		///  Returns a Typed CourseGroup Entity 
		///</summary>
		public virtual CourseGroup Copy()
		{
			return this.Copy(null);	
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone()
		{
			return this.Copy(null);
		}
		
		///<summary>
		/// ICloneableEx.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone(IDictionary existingCopies)
		{
			return this.Copy(existingCopies);
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x == null)
				return null;
				
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x, IDictionary existingCopies)
		{
			if (x == null)
				return null;
			
			if (x is ICloneableEx)
			{
				// Return a deep copy of the object
				return ((ICloneableEx)x).Clone(existingCopies);
			}
			else if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable or IClonableEx Interface.");
		}
		
		
		///<summary>
		///  Returns a Typed CourseGroup Entity which is a deep copy of the current entity.
		///</summary>
		public virtual CourseGroup DeepCopy()
		{
			return EntityHelper.Clone<CourseGroup>(this as CourseGroup);	
		}
		#endregion
		
		#region Methods	
			
		///<summary>
		/// Revert all changes and restore original values.
		///</summary>
		public override void CancelChanges()
		{
			IEditableObject obj = (IEditableObject) this;
			obj.CancelEdit();

			this.entityData = null;
			if (this._originalData != null)
			{
				this.entityData = this._originalData.Clone() as CourseGroupEntityData;
			}
			else
			{
				//Since this had no _originalData, then just reset the entityData with a new one.  entityData cannot be null.
				this.entityData = new CourseGroupEntityData();
			}
		}	
		
		/// <summary>
		/// Accepts the changes made to this object.
		/// </summary>
		/// <remarks>
		/// After calling this method, properties: IsDirty, IsNew are false. IsDeleted flag remains unchanged as it is handled by the parent List.
		/// </remarks>
		public override void AcceptChanges()
		{
			base.AcceptChanges();

			// we keep of the original version of the data
			this._originalData = null;
			this._originalData = this.entityData.Clone() as CourseGroupEntityData;
		}
		
		#region Comparision with original data
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="column">The column.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool IsPropertyChanged(CourseGroupColumn column)
		{
			switch(column)
			{
					case CourseGroupColumn.CourseGroupId:
					return entityData.CourseGroupId != _originalData.CourseGroupId;
					case CourseGroupColumn.Name:
					return entityData.Name != _originalData.Name;
					case CourseGroupColumn.Note:
					return entityData.Note != _originalData.Note;
			
				default:
					return false;
			}
		}
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="columnName">The column name.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public override bool IsPropertyChanged(string columnName)
		{
			return 	IsPropertyChanged(EntityHelper.GetEnumValue< CourseGroupColumn >(columnName));
		}
		
		/// <summary>
		/// Determines whether the data has changed from original.
		/// </summary>
		/// <returns>
		/// 	<c>true</c> if data has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool HasDataChanged()
		{
			bool result = false;
			result = result || entityData.CourseGroupId != _originalData.CourseGroupId;
			result = result || entityData.Name != _originalData.Name;
			result = result || entityData.Note != _originalData.Note;
			return result;
		}	
		
		///<summary>
		///  Returns a CourseGroup Entity with the original data.
		///</summary>
		public CourseGroup GetOriginalEntity()
		{
			if (_originalData != null)
				return CreateCourseGroup(
				_originalData.CourseGroupId,
				_originalData.Name,
				_originalData.Note
				);
				
			return (CourseGroup)this.Clone();
		}
		#endregion
	
	#region Value Semantics Instance Equality
        ///<summary>
        /// Returns a value indicating whether this instance is equal to a specified object using value semantics.
        ///</summary>
        ///<param name="Object1">An object to compare to this instance.</param>
        ///<returns>true if Object1 is a <see cref="CourseGroupBase"/> and has the same value as this instance; otherwise, false.</returns>
        public override bool Equals(object Object1)
        {
			// Cast exception if Object1 is null or DbNull
			if (Object1 != null && Object1 != DBNull.Value && Object1 is CourseGroupBase)
				return ValueEquals(this, (CourseGroupBase)Object1);
			else
				return false;
        }

        /// <summary>
		/// Serves as a hash function for a particular type, suitable for use in hashing algorithms and data structures like a hash table.
        /// Provides a hash function that is appropriate for <see cref="CourseGroupBase"/> class 
        /// and that ensures a better distribution in the hash table
        /// </summary>
        /// <returns>number (hash code) that corresponds to the value of an object</returns>
        public override int GetHashCode()
        {
			return this.CourseGroupId.GetHashCode() ^ 
					((this.Name == null) ? string.Empty : this.Name.ToString()).GetHashCode() ^ 
					((this.Note == null) ? string.Empty : this.Note.ToString()).GetHashCode();
        }
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object using value semantics.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="CourseGroupBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(CourseGroupBase toObject)
		{
			if (toObject == null)
				return false;
			return ValueEquals(this, toObject);
		}
		#endregion
		
		///<summary>
		/// Determines whether the specified <see cref="CourseGroupBase"/> instances are considered equal using value semantics.
		///</summary>
		///<param name="Object1">The first <see cref="CourseGroupBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="CourseGroupBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool ValueEquals(CourseGroupBase Object1, CourseGroupBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;
				
			bool equal = true;
			if (Object1.CourseGroupId != Object2.CourseGroupId)
				equal = false;
			if ( Object1.Name != null && Object2.Name != null )
			{
				if (Object1.Name != Object2.Name)
					equal = false;
			}
			else if (Object1.Name == null ^ Object2.Name == null )
			{
				equal = false;
			}
			if ( Object1.Note != null && Object2.Note != null )
			{
				if (Object1.Note != Object2.Note)
					equal = false;
			}
			else if (Object1.Note == null ^ Object2.Note == null )
			{
				equal = false;
			}
					
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
			//return this. GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]) .CompareTo(((CourseGroupBase)obj).GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]));
		}
		
		/*
		// static method to get a Comparer object
        public static CourseGroupComparer GetComparer()
        {
            return new CourseGroupComparer();
        }
        */

        // Comparer delegates back to CourseGroup
        // Employee uses the integer's default
        // CompareTo method
        /*
        public int CompareTo(Item rhs)
        {
            return this.Id.CompareTo(rhs.Id);
        }
        */

/*
        // Special implementation to be called by custom comparer
        public int CompareTo(CourseGroup rhs, CourseGroupColumn which)
        {
            switch (which)
            {
            	
            	
            	case CourseGroupColumn.CourseGroupId:
            		return this.CourseGroupId.CompareTo(rhs.CourseGroupId);
            		
            		                 
            	
            	
            	case CourseGroupColumn.Name:
            		return this.Name.CompareTo(rhs.Name);
            		
            		                 
            	
            	
            	case CourseGroupColumn.Note:
            		return this.Note.CompareTo(rhs.Note);
            		
            		                 
            }
            return 0;
        }
        */
	
		#endregion
		
		#region IComponent Members
		
		private ISite _site = null;

		/// <summary>
		/// Gets or Sets the site where this data is located.
		/// </summary>
		[XmlIgnore]
		[SoapIgnore]
		[Browsable(false)]
		public ISite Site
		{
			get{ return this._site; }
			set{ this._site = value; }
		}

		#endregion

		#region IDisposable Members
		
		/// <summary>
		/// Notify those that care when we dispose.
		/// </summary>
		[field:NonSerialized]
		public event System.EventHandler Disposed;

		/// <summary>
		/// Clean up. Nothing here though.
		/// </summary>
		public virtual void Dispose()
		{
			this.parentCollection = null;
			this.Dispose(true);
			GC.SuppressFinalize(this);
		}
		
		/// <summary>
		/// Clean up.
		/// </summary>
		protected virtual void Dispose(bool disposing)
		{
			if (disposing)
			{
				EventHandler handler = Disposed;
				if (handler != null)
					handler(this, EventArgs.Empty);
			}
		}
		
		#endregion
				
		#region IEntityKey<CourseGroupKey> Members
		
		// member variable for the EntityId property
		private CourseGroupKey _entityId;

		/// <summary>
		/// Gets or sets the EntityId property.
		/// </summary>
		[XmlIgnore]
		public virtual CourseGroupKey EntityId
		{
			get
			{
				if ( _entityId == null )
				{
					_entityId = new CourseGroupKey(this);
				}

				return _entityId;
			}
			set
			{
				if ( value != null )
				{
					value.Entity = this;
				}
				
				_entityId = value;
			}
		}
		
		#endregion
		
		#region EntityState
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false) , XmlIgnoreAttribute()]
		public override EntityState EntityState 
		{ 
			get{ return entityData.EntityState;	 } 
			set{ entityData.EntityState = value; } 
		}
		#endregion 
		
		#region EntityTrackingKey
		///<summary>
		/// Provides the tracking key for the <see cref="EntityLocator"/>
		///</summary>
		[XmlIgnore]
		public override string EntityTrackingKey
		{
			get
			{
				if(entityTrackingKey == null)
					entityTrackingKey = new System.Text.StringBuilder("CourseGroup")
					.Append("|").Append( this.CourseGroupId.ToString()).ToString();
				return entityTrackingKey;
			}
			set
		    {
		        if (value != null)
                    entityTrackingKey = value;
		    }
		}
		#endregion 
		
		#region ToString Method
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{4}{3}- CourseGroupId: {0}{3}- Name: {1}{3}- Note: {2}{3}{5}", 
				this.CourseGroupId,
				(this.Name == null) ? string.Empty : this.Name.ToString(),
				(this.Note == null) ? string.Empty : this.Note.ToString(),
				System.Environment.NewLine, 
				this.GetType(),
				this.Error.Length == 0 ? string.Empty : string.Format("- Error: {0}\n",this.Error));
		}
		
		#endregion ToString Method
		
		#region Inner data class
		
	/// <summary>
	///		The data structure representation of the 'CourseGroup' table.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Serializable]
	internal protected class CourseGroupEntityData : ICloneable, ICloneableEx
	{
		#region Variable Declarations
		private EntityState currentEntityState = EntityState.Added;
		
		#region Primary key(s)
		/// <summary>			
		/// CourseGroupId : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "CourseGroup"</remarks>
		public System.Int32 CourseGroupId;
			
		/// <summary>
		/// keep a copy of the original so it can be used for editable primary keys.
		/// </summary>
		public System.Int32 OriginalCourseGroupId;
		
		#endregion
		
		#region Non Primary key(s)
		
		
		/// <summary>
		/// Name : 
		/// </summary>
		public System.String		  Name = null;
		
		/// <summary>
		/// Note : 
		/// </summary>
		public System.String		  Note = null;
		#endregion
			
		#region Source Foreign Key Property
				
		#endregion
		#endregion Variable Declarations
	
		#region Data Properties

		#region CourseDetailsCollection
		
		private TList<CourseDetails> _courseDetailsCourseGroup;
		
		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation _courseDetailsCourseGroup
		/// </summary>
		
		public TList<CourseDetails> CourseDetailsCollection
		{
			get
			{
				if (_courseDetailsCourseGroup == null)
				{
				_courseDetailsCourseGroup = new TList<CourseDetails>();
				}
	
				return _courseDetailsCourseGroup;
			}
			set { _courseDetailsCourseGroup = value; }
		}
		
		#endregion

		#endregion Data Properties
		
		#region Clone Method

		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public Object Clone()
		{
			CourseGroupEntityData _tmp = new CourseGroupEntityData();
						
			_tmp.CourseGroupId = this.CourseGroupId;
			_tmp.OriginalCourseGroupId = this.OriginalCourseGroupId;
			
			_tmp.Name = this.Name;
			_tmp.Note = this.Note;
			
			#region Source Parent Composite Entities
			#endregion
		
			#region Child Collections
			//deep copy nested objects
			if (this._courseDetailsCourseGroup != null)
				_tmp.CourseDetailsCollection = (TList<CourseDetails>) MakeCopyOf(this.CourseDetailsCollection); 
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public object Clone(IDictionary existingCopies)
		{
			if (existingCopies == null)
				existingCopies = new Hashtable();
				
			CourseGroupEntityData _tmp = new CourseGroupEntityData();
						
			_tmp.CourseGroupId = this.CourseGroupId;
			_tmp.OriginalCourseGroupId = this.OriginalCourseGroupId;
			
			_tmp.Name = this.Name;
			_tmp.Note = this.Note;
			
			#region Source Parent Composite Entities
			#endregion
		
			#region Child Collections
			//deep copy nested objects
			_tmp.CourseDetailsCollection = (TList<CourseDetails>) MakeCopyOf(this.CourseDetailsCollection, existingCopies); 
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		#endregion Clone Method
		
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public EntityState	EntityState
		{
			get { return currentEntityState;  }
			set { currentEntityState = value; }
		}
	
	}//End struct











		#endregion
		
				
		
		#region Events trigger
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="CourseGroupColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanging(CourseGroupColumn column)
		{
			OnColumnChanging(column, null);
			return;
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="CourseGroupColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanged(CourseGroupColumn column)
		{
			OnColumnChanged(column, null);
			return;
		} 
		
		
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="CourseGroupColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanging(CourseGroupColumn column, object value)
		{
			if(IsEntityTracked && EntityState != EntityState.Added && !EntityManager.TrackChangedEntities)
				EntityManager.StopTracking(entityTrackingKey);
				
			if (!SuppressEntityEvents)
			{
				CourseGroupEventHandler handler = ColumnChanging;
				if(handler != null)
				{
					handler(this, new CourseGroupEventArgs(column, value));
				}
			}
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="CourseGroupColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanged(CourseGroupColumn column, object value)
		{
			if (!SuppressEntityEvents)
			{
				CourseGroupEventHandler handler = ColumnChanged;
				if(handler != null)
				{
					handler(this, new CourseGroupEventArgs(column, value));
				}
			
				// warn the parent list that i have changed
				OnEntityChanged();
			}
		} 
		#endregion
			
	} // End Class
	
	
	#region CourseGroupEventArgs class
	/// <summary>
	/// Provides data for the ColumnChanging and ColumnChanged events.
	/// </summary>
	/// <remarks>
	/// The ColumnChanging and ColumnChanged events occur when a change is made to the value 
	/// of a property of a <see cref="CourseGroup"/> object.
	/// </remarks>
	public class CourseGroupEventArgs : System.EventArgs
	{
		private CourseGroupColumn column;
		private object value;
		
		///<summary>
		/// Initalizes a new Instance of the CourseGroupEventArgs class.
		///</summary>
		public CourseGroupEventArgs(CourseGroupColumn column)
		{
			this.column = column;
		}
		
		///<summary>
		/// Initalizes a new Instance of the CourseGroupEventArgs class.
		///</summary>
		public CourseGroupEventArgs(CourseGroupColumn column, object value)
		{
			this.column = column;
			this.value = value;
		}
		
		///<summary>
		/// The CourseGroupColumn that was modified, which has raised the event.
		///</summary>
		///<value cref="CourseGroupColumn" />
		public CourseGroupColumn Column { get { return this.column; } }
		
		/// <summary>
        /// Gets the current value of the column.
        /// </summary>
        /// <value>The current value of the column.</value>
		public object Value{ get { return this.value; } }

	}
	#endregion
	
	///<summary>
	/// Define a delegate for all CourseGroup related events.
	///</summary>
	public delegate void CourseGroupEventHandler(object sender, CourseGroupEventArgs e);
	
	#region CourseGroupComparer
		
	/// <summary>
	///	Strongly Typed IComparer
	/// </summary>
	public class CourseGroupComparer : System.Collections.Generic.IComparer<CourseGroup>
	{
		CourseGroupColumn whichComparison;
		
		/// <summary>
        /// Initializes a new instance of the <see cref="T:CourseGroupComparer"/> class.
        /// </summary>
		public CourseGroupComparer()
        {            
        }               
        
        /// <summary>
        /// Initializes a new instance of the <see cref="T:CourseGroupComparer"/> class.
        /// </summary>
        /// <param name="column">The column to sort on.</param>
        public CourseGroupComparer(CourseGroupColumn column)
        {
            this.whichComparison = column;
        }

		/// <summary>
        /// Determines whether the specified <c cref="CourseGroup"/> instances are considered equal.
        /// </summary>
        /// <param name="a">The first <c cref="CourseGroup"/> to compare.</param>
        /// <param name="b">The second <c>CourseGroup</c> to compare.</param>
        /// <returns>true if objA is the same instance as objB or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
        public bool Equals(CourseGroup a, CourseGroup b)
        {
            return this.Compare(a, b) == 0;
        }

		/// <summary>
        /// Gets the hash code of the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns></returns>
        public int GetHashCode(CourseGroup entity)
        {
            return entity.GetHashCode();
        }

        /// <summary>
        /// Performs a case-insensitive comparison of two objects of the same type and returns a value indicating whether one is less than, equal to, or greater than the other.
        /// </summary>
        /// <param name="a">The first object to compare.</param>
        /// <param name="b">The second object to compare.</param>
        /// <returns></returns>
        public int Compare(CourseGroup a, CourseGroup b)
        {
        	EntityPropertyComparer entityPropertyComparer = new EntityPropertyComparer(this.whichComparison.ToString());
        	return entityPropertyComparer.Compare(a, b);
        }

		/// <summary>
        /// Gets or sets the column that will be used for comparison.
        /// </summary>
        /// <value>The comparison column.</value>
        public CourseGroupColumn WhichComparison
        {
            get { return this.whichComparison; }
            set { this.whichComparison = value; }
        }
	}
	
	#endregion
	
	#region CourseGroupKey Class

	/// <summary>
	/// Wraps the unique identifier values for the <see cref="CourseGroup"/> object.
	/// </summary>
	[Serializable]
	[CLSCompliant(true)]
	public class CourseGroupKey : EntityKeyBase
	{
		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the CourseGroupKey class.
		/// </summary>
		public CourseGroupKey()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the CourseGroupKey class.
		/// </summary>
		public CourseGroupKey(CourseGroupBase entity)
		{
			this.Entity = entity;

			#region Init Properties

			if ( entity != null )
			{
				this.CourseGroupId = entity.CourseGroupId;
			}

			#endregion
		}
		
		/// <summary>
		/// Initializes a new instance of the CourseGroupKey class.
		/// </summary>
		public CourseGroupKey(System.Int32 _courseGroupId)
		{
			#region Init Properties

			this.CourseGroupId = _courseGroupId;

			#endregion
		}
		
		#endregion Constructors

		#region Properties
		
		// member variable for the Entity property
		private CourseGroupBase _entity;
		
		/// <summary>
		/// Gets or sets the Entity property.
		/// </summary>
		public CourseGroupBase Entity
		{
			get { return _entity; }
			set { _entity = value; }
		}
		
		// member variable for the CourseGroupId property
		private System.Int32 _courseGroupId;
		
		/// <summary>
		/// Gets or sets the CourseGroupId property.
		/// </summary>
		public System.Int32 CourseGroupId
		{
			get { return _courseGroupId; }
			set
			{
				if ( this.Entity != null )
					this.Entity.CourseGroupId = value;
				
				_courseGroupId = value;
			}
		}
		
		#endregion

		#region Methods
		
		/// <summary>
		/// Reads values from the supplied <see cref="IDictionary"/> object into
		/// properties of the current object.
		/// </summary>
		/// <param name="values">An <see cref="IDictionary"/> instance that contains
		/// the key/value pairs to be used as property values.</param>
		public override void Load(IDictionary values)
		{
			#region Init Properties

			if ( values != null )
			{
				CourseGroupId = ( values["CourseGroupId"] != null ) ? (System.Int32) EntityUtil.ChangeType(values["CourseGroupId"], typeof(System.Int32)) : (int)0;
			}

			#endregion
		}

		/// <summary>
		/// Creates a new <see cref="IDictionary"/> object and populates it
		/// with the property values of the current object.
		/// </summary>
		/// <returns>A collection of name/value pairs.</returns>
		public override IDictionary ToDictionary()
		{
			IDictionary values = new Hashtable();

			#region Init Dictionary

			values.Add("CourseGroupId", CourseGroupId);

			#endregion Init Dictionary

			return values;
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return String.Format("CourseGroupId: {0}{1}",
								CourseGroupId,
								System.Environment.NewLine);
		}

		#endregion Methods
	}
	
	#endregion	

	#region CourseGroupColumn Enum
	
	/// <summary>
	/// Enumerate the CourseGroup columns.
	/// </summary>
	[Serializable]
	public enum CourseGroupColumn : int
	{
		/// <summary>
		/// CourseGroupId : 
		/// </summary>
		[EnumTextValue("CourseGroupId")]
		[ColumnEnum("CourseGroupId", typeof(System.Int32), System.Data.DbType.Int32, true, false, false)]
		CourseGroupId = 1,
		/// <summary>
		/// Name : 
		/// </summary>
		[EnumTextValue("Name")]
		[ColumnEnum("Name", typeof(System.String), System.Data.DbType.String, false, false, true, 50)]
		Name = 2,
		/// <summary>
		/// Note : 
		/// </summary>
		[EnumTextValue("Note")]
		[ColumnEnum("Note", typeof(System.String), System.Data.DbType.String, false, false, true, 1024)]
		Note = 3
	}//End enum

	#endregion CourseGroupColumn Enum

} // end namespace
