using System;
using System.ComponentModel;

namespace AIProject.Entities
{
	/// <summary>
	///		The data structure representation of the 'TeacherDetails' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface ITeacherDetails 
	{
		/// <summary>			
		/// TeacherId : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "TeacherDetails"</remarks>
		System.Int32 TeacherId { get; set; }
				
		
		
		/// <summary>
		/// TeacherName : 
		/// </summary>
		System.String  TeacherName  { get; set; }
		
		/// <summary>
		/// TeacherCertificate : 
		/// </summary>
		System.Int32?  TeacherCertificate  { get; set; }
		
		/// <summary>
		/// Note : 
		/// </summary>
		System.String  Note  { get; set; }
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties


		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation _classDetailsTeacherId
		/// </summary>	
		TList<ClassDetails> ClassDetailsCollection {  get;  set;}	

		#endregion Data Properties

	}
}


