using System;
using System.ComponentModel;

namespace AIDT.Entities
{
	/// <summary>
	///		The data structure representation of the 'ClassTime' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface IClassTime 
	{
		/// <summary>			
		/// ClassTimeId : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "ClassTime"</remarks>
		System.Int32 ClassTimeId { get; set; }
				
		/// <summary>
		/// keep a copy of the original so it can be used for editable primary keys.
		/// </summary>
		System.Int32 OriginalClassTimeId { get; set; }
			
		
		
		/// <summary>
		/// TimeName : 
		/// </summary>
		System.String  TimeName  { get; set; }
		
		/// <summary>
		/// Note : 
		/// </summary>
		System.String  Note  { get; set; }
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties


		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation _classDetailsClassTime
		/// </summary>	
		TList<ClassDetails> ClassDetailsCollection {  get;  set;}	

		#endregion Data Properties

	}
}


