using System;
using System.ComponentModel;

namespace AIDT.Entities
{
	/// <summary>
	///		The data structure representation of the 'ClassArrangement' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface IClassArrangement 
	{
		/// <summary>			
		/// CustomerId : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "ClassArrangement"</remarks>
		System.Int32 CustomerId { get; set; }
				
		/// <summary>
		/// keep a copy of the original so it can be used for editable primary keys.
		/// </summary>
		System.Int32 OriginalCustomerId { get; set; }
			
		/// <summary>			
		/// ClassId : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "ClassArrangement"</remarks>
		System.Int32 ClassId { get; set; }
				
		/// <summary>
		/// keep a copy of the original so it can be used for editable primary keys.
		/// </summary>
		System.Int32 OriginalClassId { get; set; }
			
		/// <summary>			
		/// CreateDate : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "ClassArrangement"</remarks>
		System.DateTime CreateDate { get; set; }
				
		/// <summary>
		/// keep a copy of the original so it can be used for editable primary keys.
		/// </summary>
		System.DateTime OriginalCreateDate { get; set; }
			
		
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties

		#endregion Data Properties

	}
}


