
/*
	File generated by NetTiers templates [www.nettiers.com]
	Important: Do not modify this file. Edit the file ClassArrangement.cs instead.
*/

#region using directives
using System;
using System.ComponentModel;
using System.Collections;
using System.Xml.Serialization;
using System.Runtime.Serialization;

using AIProject.Entities.Validation;
#endregion

namespace AIProject.Entities
{
	///<summary>
	/// An object representation of the 'ClassArrangement' table. [No description found the database]	
	///</summary>
	[Serializable]
	[DataObject, CLSCompliant(true)]
	public abstract partial class ClassArrangementBase : EntityBase, IClassArrangement, IEntityId<ClassArrangementKey>, System.IComparable, System.ICloneable, ICloneableEx, IEditableObject, IComponent, INotifyPropertyChanged
	{		
		#region Variable Declarations
		
		/// <summary>
		///  Hold the inner data of the entity.
		/// </summary>
		private ClassArrangementEntityData entityData;
		
		/// <summary>
		/// 	Hold the original data of the entity, as loaded from the repository.
		/// </summary>
		private ClassArrangementEntityData _originalData;
		
		/// <summary>
		/// 	Hold a backup of the inner data of the entity.
		/// </summary>
		private ClassArrangementEntityData backupData; 
		
		/// <summary>
		/// 	Key used if Tracking is Enabled for the <see cref="EntityLocator" />.
		/// </summary>
		private string entityTrackingKey;
		
		/// <summary>
		/// 	Hold the parent TList&lt;entity&gt; in which this entity maybe contained.
		/// </summary>
		/// <remark>Mostly used for databinding</remark>
		[NonSerialized]
		private TList<ClassArrangement> parentCollection;
		
		private bool inTxn = false;
		
		/// <summary>
		/// Occurs when a value is being changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event ClassArrangementEventHandler ColumnChanging;		
		
		/// <summary>
		/// Occurs after a value has been changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event ClassArrangementEventHandler ColumnChanged;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="ClassArrangementBase"/> instance.
		///</summary>
		public ClassArrangementBase()
		{
			this.entityData = new ClassArrangementEntityData();
			this.backupData = null;
		}		
		
		///<summary>
		/// Creates a new <see cref="ClassArrangementBase"/> instance.
		///</summary>
		///<param name="_customerId"></param>
		///<param name="_classId"></param>
		///<param name="_createDate"></param>
		public ClassArrangementBase(System.Int32 _customerId, System.Int32 _classId, System.DateTime _createDate)
		{
			this.entityData = new ClassArrangementEntityData();
			this.backupData = null;

			this.CustomerId = _customerId;
			this.ClassId = _classId;
			this.CreateDate = _createDate;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="ClassArrangement"/> instance.
		///</summary>
		///<param name="_customerId"></param>
		///<param name="_classId"></param>
		///<param name="_createDate"></param>
		public static ClassArrangement CreateClassArrangement(System.Int32 _customerId, System.Int32 _classId, System.DateTime _createDate)
		{
			ClassArrangement newClassArrangement = new ClassArrangement();
			newClassArrangement.CustomerId = _customerId;
			newClassArrangement.ClassId = _classId;
			newClassArrangement.CreateDate = _createDate;
			return newClassArrangement;
		}
				
		#endregion Constructors
			
		#region Properties	
		
		#region Data Properties		
		/// <summary>
		/// 	Gets or sets the CustomerId property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, false, false)]
		public virtual System.Int32 CustomerId
		{
			get
			{
				return this.entityData.CustomerId; 
			}
			
			set
			{
				if (this.entityData.CustomerId == value)
					return;
					
				OnColumnChanging(ClassArrangementColumn.CustomerId, this.entityData.CustomerId);
				this.entityData.CustomerId = value;
				this.EntityId.CustomerId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(ClassArrangementColumn.CustomerId, this.entityData.CustomerId);
				OnPropertyChanged("CustomerId");
			}
		}
		
		/// <summary>
		/// 	Get the original value of the CustomerId property.
		///		
		/// </summary>
		/// <remarks>This is the original value of the CustomerId property.</remarks>
		/// <value>This type is int</value>
		[BrowsableAttribute(false)/*, XmlIgnoreAttribute()*/]
		public  virtual System.Int32 OriginalCustomerId
		{
			get { return this.entityData.OriginalCustomerId; }
			set { this.entityData.OriginalCustomerId = value; }
		}
		
		/// <summary>
		/// 	Gets or sets the ClassId property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, false, false)]
		public virtual System.Int32 ClassId
		{
			get
			{
				return this.entityData.ClassId; 
			}
			
			set
			{
				if (this.entityData.ClassId == value)
					return;
					
				OnColumnChanging(ClassArrangementColumn.ClassId, this.entityData.ClassId);
				this.entityData.ClassId = value;
				this.EntityId.ClassId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(ClassArrangementColumn.ClassId, this.entityData.ClassId);
				OnPropertyChanged("ClassId");
			}
		}
		
		/// <summary>
		/// 	Get the original value of the ClassId property.
		///		
		/// </summary>
		/// <remarks>This is the original value of the ClassId property.</remarks>
		/// <value>This type is int</value>
		[BrowsableAttribute(false)/*, XmlIgnoreAttribute()*/]
		public  virtual System.Int32 OriginalClassId
		{
			get { return this.entityData.OriginalClassId; }
			set { this.entityData.OriginalClassId = value; }
		}
		
		/// <summary>
		/// 	Gets or sets the CreateDate property. 
		///		
		/// </summary>
		/// <value>This type is datetime.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, false, false)]
		public virtual System.DateTime CreateDate
		{
			get
			{
				return this.entityData.CreateDate; 
			}
			
			set
			{
				if (this.entityData.CreateDate == value)
					return;
					
				OnColumnChanging(ClassArrangementColumn.CreateDate, this.entityData.CreateDate);
				this.entityData.CreateDate = value;
				this.EntityId.CreateDate = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(ClassArrangementColumn.CreateDate, this.entityData.CreateDate);
				OnPropertyChanged("CreateDate");
			}
		}
		
		/// <summary>
		/// 	Get the original value of the CreateDate property.
		///		
		/// </summary>
		/// <remarks>This is the original value of the CreateDate property.</remarks>
		/// <value>This type is datetime</value>
		[BrowsableAttribute(false)/*, XmlIgnoreAttribute()*/]
		public  virtual System.DateTime OriginalCreateDate
		{
			get { return this.entityData.OriginalCreateDate; }
			set { this.entityData.OriginalCreateDate = value; }
		}
		
		#endregion Data Properties		

		#region Source Foreign Key Property
				
		/// <summary>
		/// Gets or sets the source <see cref="ClassDetails"/>.
		/// </summary>
		/// <value>The source ClassDetails for ClassId.</value>
        [XmlIgnore()]
		[Browsable(false), System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual ClassDetails ClassIdSource
      	{
            get { return entityData.ClassIdSource; }
            set { entityData.ClassIdSource = value; }
      	}
		/// <summary>
		/// Gets or sets the source <see cref="CustomerDetails"/>.
		/// </summary>
		/// <value>The source CustomerDetails for CustomerId.</value>
        [XmlIgnore()]
		[Browsable(false), System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual CustomerDetails CustomerIdSource
      	{
            get { return entityData.CustomerIdSource; }
            set { entityData.CustomerIdSource = value; }
      	}
		#endregion
		
		#region Children Collections
		#endregion Children Collections
		
		#endregion
		#region Validation
		
		/// <summary>
		/// Assigns validation rules to this object based on model definition.
		/// </summary>
		/// <remarks>This method overrides the base class to add schema related validation.</remarks>
		protected override void AddValidationRules()
		{
			//Validation rules based on database schema.
		}
   		#endregion
		
		#region Table Meta Data
		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string TableName
		{
			get { return "ClassArrangement"; }
		}
		
		/// <summary>
		///		The name of the underlying database table's columns.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string[] TableColumns
		{
			get
			{
				return new string[] {"CustomerId", "ClassId", "CreateDate"};
			}
		}
		#endregion 
		
		#region IEditableObject
		
		#region  CancelAddNew Event
		/// <summary>
        /// The delegate for the CancelAddNew event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		public delegate void CancelAddNewEventHandler(object sender, EventArgs e);
    
    	/// <summary>
		/// The CancelAddNew event.
		/// </summary>
		[field:NonSerialized]
		public event CancelAddNewEventHandler CancelAddNew ;

		/// <summary>
        /// Called when [cancel add new].
        /// </summary>
        public void OnCancelAddNew()
        {    
			if (!SuppressEntityEvents)
			{
	            CancelAddNewEventHandler handler = CancelAddNew ;
            	if (handler != null)
	            {    
    	            handler(this, EventArgs.Empty) ;
        	    }
	        }
        }
		#endregion 
		
		/// <summary>
		/// Begins an edit on an object.
		/// </summary>
		void IEditableObject.BeginEdit() 
	    {
	        //Console.WriteLine("Start BeginEdit");
	        if (!inTxn) 
	        {
	            this.backupData = this.entityData.Clone() as ClassArrangementEntityData;
	            inTxn = true;
	            //Console.WriteLine("BeginEdit");
	        }
	        //Console.WriteLine("End BeginEdit");
	    }
	
		/// <summary>
		/// Discards changes since the last <c>BeginEdit</c> call.
		/// </summary>
	    void IEditableObject.CancelEdit() 
	    {
	        //Console.WriteLine("Start CancelEdit");
	        if (this.inTxn) 
	        {
	            this.entityData = this.backupData;
	            this.backupData = null;
				this.inTxn = false;

				if (this.bindingIsNew)
	        	//if (this.EntityState == EntityState.Added)
	        	{
					if (this.parentCollection != null)
						this.parentCollection.Remove( (ClassArrangement) this ) ;
				}	            
	        }
	        //Console.WriteLine("End CancelEdit");
	    }
	
		/// <summary>
		/// Pushes changes since the last <c>BeginEdit</c> or <c>IBindingList.AddNew</c> call into the underlying object.
		/// </summary>
	    void IEditableObject.EndEdit() 
	    {
	        //Console.WriteLine("Start EndEdit" + this.custData.id + this.custData.lastName);
	        if (this.inTxn) 
	        {
	            this.backupData = null;
				if (this.IsDirty) 
				{
					if (this.bindingIsNew) {
						this.EntityState = EntityState.Added;
						this.bindingIsNew = false ;
					}
					else
						if (this.EntityState == EntityState.Unchanged) 
							this.EntityState = EntityState.Changed ;
				}

				this.bindingIsNew = false ;
	            this.inTxn = false;	            
	        }
	        //Console.WriteLine("End EndEdit");
	    }
	    
	    /// <summary>
        /// Gets or sets the parent collection of this current entity, if available.
        /// </summary>
        /// <value>The parent collection.</value>
	    [XmlIgnore]
		[Browsable(false)]
	    public override object ParentCollection
	    {
	        get 
	        {
	            return this.parentCollection;
	        }
	        set 
	        {
	            this.parentCollection = value as TList<ClassArrangement>;
	        }
	    }
	    
	    /// <summary>
        /// Called when the entity is changed.
        /// </summary>
	    private void OnEntityChanged() 
	    {
	        if (!SuppressEntityEvents && !inTxn && this.parentCollection != null) 
	        {
	            this.parentCollection.EntityChanged(this as ClassArrangement);
	        }
	    }


		#endregion
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed ClassArrangement Entity 
		///</summary>
		protected virtual ClassArrangement Copy(IDictionary existingCopies)
		{
			if (existingCopies == null)
			{
				// This is the root of the tree to be copied!
				existingCopies = new Hashtable();
			}

			//shallow copy entity
			ClassArrangement copy = new ClassArrangement();
			existingCopies.Add(this, copy);
			copy.SuppressEntityEvents = true;
				copy.CustomerId = this.CustomerId;
					copy.OriginalCustomerId = this.OriginalCustomerId;
				copy.ClassId = this.ClassId;
					copy.OriginalClassId = this.OriginalClassId;
				copy.CreateDate = this.CreateDate;
					copy.OriginalCreateDate = this.OriginalCreateDate;
			
			if (this.ClassIdSource != null && existingCopies.Contains(this.ClassIdSource))
				copy.ClassIdSource = existingCopies[this.ClassIdSource] as ClassDetails;
			else
				copy.ClassIdSource = MakeCopyOf(this.ClassIdSource, existingCopies) as ClassDetails;
			if (this.CustomerIdSource != null && existingCopies.Contains(this.CustomerIdSource))
				copy.CustomerIdSource = existingCopies[this.CustomerIdSource] as CustomerDetails;
			else
				copy.CustomerIdSource = MakeCopyOf(this.CustomerIdSource, existingCopies) as CustomerDetails;
		
			copy.EntityState = this.EntityState;
			copy.SuppressEntityEvents = false;
			return copy;
		}		
		
		
		
		///<summary>
		///  Returns a Typed ClassArrangement Entity 
		///</summary>
		public virtual ClassArrangement Copy()
		{
			return this.Copy(null);	
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone()
		{
			return this.Copy(null);
		}
		
		///<summary>
		/// ICloneableEx.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone(IDictionary existingCopies)
		{
			return this.Copy(existingCopies);
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x == null)
				return null;
				
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x, IDictionary existingCopies)
		{
			if (x == null)
				return null;
			
			if (x is ICloneableEx)
			{
				// Return a deep copy of the object
				return ((ICloneableEx)x).Clone(existingCopies);
			}
			else if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable or IClonableEx Interface.");
		}
		
		
		///<summary>
		///  Returns a Typed ClassArrangement Entity which is a deep copy of the current entity.
		///</summary>
		public virtual ClassArrangement DeepCopy()
		{
			return EntityHelper.Clone<ClassArrangement>(this as ClassArrangement);	
		}
		#endregion
		
		#region Methods	
			
		///<summary>
		/// Revert all changes and restore original values.
		///</summary>
		public override void CancelChanges()
		{
			IEditableObject obj = (IEditableObject) this;
			obj.CancelEdit();

			this.entityData = null;
			if (this._originalData != null)
			{
				this.entityData = this._originalData.Clone() as ClassArrangementEntityData;
			}
			else
			{
				//Since this had no _originalData, then just reset the entityData with a new one.  entityData cannot be null.
				this.entityData = new ClassArrangementEntityData();
			}
		}	
		
		/// <summary>
		/// Accepts the changes made to this object.
		/// </summary>
		/// <remarks>
		/// After calling this method, properties: IsDirty, IsNew are false. IsDeleted flag remains unchanged as it is handled by the parent List.
		/// </remarks>
		public override void AcceptChanges()
		{
			base.AcceptChanges();

			// we keep of the original version of the data
			this._originalData = null;
			this._originalData = this.entityData.Clone() as ClassArrangementEntityData;
		}
		
		#region Comparision with original data
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="column">The column.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool IsPropertyChanged(ClassArrangementColumn column)
		{
			switch(column)
			{
					case ClassArrangementColumn.CustomerId:
					return entityData.CustomerId != _originalData.CustomerId;
					case ClassArrangementColumn.ClassId:
					return entityData.ClassId != _originalData.ClassId;
					case ClassArrangementColumn.CreateDate:
					return entityData.CreateDate != _originalData.CreateDate;
			
				default:
					return false;
			}
		}
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="columnName">The column name.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public override bool IsPropertyChanged(string columnName)
		{
			return 	IsPropertyChanged(EntityHelper.GetEnumValue< ClassArrangementColumn >(columnName));
		}
		
		/// <summary>
		/// Determines whether the data has changed from original.
		/// </summary>
		/// <returns>
		/// 	<c>true</c> if data has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool HasDataChanged()
		{
			bool result = false;
			result = result || entityData.CustomerId != _originalData.CustomerId;
			result = result || entityData.ClassId != _originalData.ClassId;
			result = result || entityData.CreateDate != _originalData.CreateDate;
			return result;
		}	
		
		///<summary>
		///  Returns a ClassArrangement Entity with the original data.
		///</summary>
		public ClassArrangement GetOriginalEntity()
		{
			if (_originalData != null)
				return CreateClassArrangement(
				_originalData.CustomerId,
				_originalData.ClassId,
				_originalData.CreateDate
				);
				
			return (ClassArrangement)this.Clone();
		}
		#endregion
	
	#region Value Semantics Instance Equality
        ///<summary>
        /// Returns a value indicating whether this instance is equal to a specified object using value semantics.
        ///</summary>
        ///<param name="Object1">An object to compare to this instance.</param>
        ///<returns>true if Object1 is a <see cref="ClassArrangementBase"/> and has the same value as this instance; otherwise, false.</returns>
        public override bool Equals(object Object1)
        {
			// Cast exception if Object1 is null or DbNull
			if (Object1 != null && Object1 != DBNull.Value && Object1 is ClassArrangementBase)
				return ValueEquals(this, (ClassArrangementBase)Object1);
			else
				return false;
        }

        /// <summary>
		/// Serves as a hash function for a particular type, suitable for use in hashing algorithms and data structures like a hash table.
        /// Provides a hash function that is appropriate for <see cref="ClassArrangementBase"/> class 
        /// and that ensures a better distribution in the hash table
        /// </summary>
        /// <returns>number (hash code) that corresponds to the value of an object</returns>
        public override int GetHashCode()
        {
			return this.CustomerId.GetHashCode() ^ 
					this.ClassId.GetHashCode() ^ 
					this.CreateDate.GetHashCode();
        }
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object using value semantics.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="ClassArrangementBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(ClassArrangementBase toObject)
		{
			if (toObject == null)
				return false;
			return ValueEquals(this, toObject);
		}
		#endregion
		
		///<summary>
		/// Determines whether the specified <see cref="ClassArrangementBase"/> instances are considered equal using value semantics.
		///</summary>
		///<param name="Object1">The first <see cref="ClassArrangementBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="ClassArrangementBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool ValueEquals(ClassArrangementBase Object1, ClassArrangementBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;
				
			bool equal = true;
			if (Object1.CustomerId != Object2.CustomerId)
				equal = false;
			if (Object1.ClassId != Object2.ClassId)
				equal = false;
			if (Object1.CreateDate != Object2.CreateDate)
				equal = false;
					
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
			//return this. GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]) .CompareTo(((ClassArrangementBase)obj).GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]));
		}
		
		/*
		// static method to get a Comparer object
        public static ClassArrangementComparer GetComparer()
        {
            return new ClassArrangementComparer();
        }
        */

        // Comparer delegates back to ClassArrangement
        // Employee uses the integer's default
        // CompareTo method
        /*
        public int CompareTo(Item rhs)
        {
            return this.Id.CompareTo(rhs.Id);
        }
        */

/*
        // Special implementation to be called by custom comparer
        public int CompareTo(ClassArrangement rhs, ClassArrangementColumn which)
        {
            switch (which)
            {
            	
            	
            	case ClassArrangementColumn.CustomerId:
            		return this.CustomerId.CompareTo(rhs.CustomerId);
            		
            		                 
            	
            	
            	case ClassArrangementColumn.ClassId:
            		return this.ClassId.CompareTo(rhs.ClassId);
            		
            		                 
            	
            	
            	case ClassArrangementColumn.CreateDate:
            		return this.CreateDate.CompareTo(rhs.CreateDate);
            		
            		                 
            }
            return 0;
        }
        */
	
		#endregion
		
		#region IComponent Members
		
		private ISite _site = null;

		/// <summary>
		/// Gets or Sets the site where this data is located.
		/// </summary>
		[XmlIgnore]
		[SoapIgnore]
		[Browsable(false)]
		public ISite Site
		{
			get{ return this._site; }
			set{ this._site = value; }
		}

		#endregion

		#region IDisposable Members
		
		/// <summary>
		/// Notify those that care when we dispose.
		/// </summary>
		[field:NonSerialized]
		public event System.EventHandler Disposed;

		/// <summary>
		/// Clean up. Nothing here though.
		/// </summary>
		public virtual void Dispose()
		{
			this.parentCollection = null;
			this.Dispose(true);
			GC.SuppressFinalize(this);
		}
		
		/// <summary>
		/// Clean up.
		/// </summary>
		protected virtual void Dispose(bool disposing)
		{
			if (disposing)
			{
				EventHandler handler = Disposed;
				if (handler != null)
					handler(this, EventArgs.Empty);
			}
		}
		
		#endregion
				
		#region IEntityKey<ClassArrangementKey> Members
		
		// member variable for the EntityId property
		private ClassArrangementKey _entityId;

		/// <summary>
		/// Gets or sets the EntityId property.
		/// </summary>
		[XmlIgnore]
		public virtual ClassArrangementKey EntityId
		{
			get
			{
				if ( _entityId == null )
				{
					_entityId = new ClassArrangementKey(this);
				}

				return _entityId;
			}
			set
			{
				if ( value != null )
				{
					value.Entity = this;
				}
				
				_entityId = value;
			}
		}
		
		#endregion
		
		#region EntityState
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false) , XmlIgnoreAttribute()]
		public override EntityState EntityState 
		{ 
			get{ return entityData.EntityState;	 } 
			set{ entityData.EntityState = value; } 
		}
		#endregion 
		
		#region EntityTrackingKey
		///<summary>
		/// Provides the tracking key for the <see cref="EntityLocator"/>
		///</summary>
		[XmlIgnore]
		public override string EntityTrackingKey
		{
			get
			{
				if(entityTrackingKey == null)
					entityTrackingKey = new System.Text.StringBuilder("ClassArrangement")
					.Append("|").Append( this.CustomerId.ToString())
					.Append("|").Append( this.ClassId.ToString())
					.Append("|").Append( this.CreateDate.ToString()).ToString();
				return entityTrackingKey;
			}
			set
		    {
		        if (value != null)
                    entityTrackingKey = value;
		    }
		}
		#endregion 
		
		#region ToString Method
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{4}{3}- CustomerId: {0}{3}- ClassId: {1}{3}- CreateDate: {2}{3}{5}", 
				this.CustomerId,
				this.ClassId,
				this.CreateDate,
				System.Environment.NewLine, 
				this.GetType(),
				this.Error.Length == 0 ? string.Empty : string.Format("- Error: {0}\n",this.Error));
		}
		
		#endregion ToString Method
		
		#region Inner data class
		
	/// <summary>
	///		The data structure representation of the 'ClassArrangement' table.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Serializable]
	internal protected class ClassArrangementEntityData : ICloneable, ICloneableEx
	{
		#region Variable Declarations
		private EntityState currentEntityState = EntityState.Added;
		
		#region Primary key(s)
		/// <summary>			
		/// CustomerId : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "ClassArrangement"</remarks>
		public System.Int32 CustomerId;
			
		/// <summary>
		/// keep a copy of the original so it can be used for editable primary keys.
		/// </summary>
		public System.Int32 OriginalCustomerId;
		
		/// <summary>			
		/// ClassId : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "ClassArrangement"</remarks>
		public System.Int32 ClassId;
			
		/// <summary>
		/// keep a copy of the original so it can be used for editable primary keys.
		/// </summary>
		public System.Int32 OriginalClassId;
		
		/// <summary>			
		/// CreateDate : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "ClassArrangement"</remarks>
		public System.DateTime CreateDate;
			
		/// <summary>
		/// keep a copy of the original so it can be used for editable primary keys.
		/// </summary>
		public System.DateTime OriginalCreateDate;
		
		#endregion
		
		#region Non Primary key(s)
		
		#endregion
			
		#region Source Foreign Key Property
				
		private ClassDetails _classIdSource = null;
		
		/// <summary>
		/// Gets or sets the source <see cref="ClassDetails"/>.
		/// </summary>
		/// <value>The source ClassDetails for ClassId.</value>
		[XmlIgnore()]
		[Browsable(false)]
		public virtual ClassDetails ClassIdSource
      	{
            get { return this._classIdSource; }
            set { this._classIdSource = value; }
      	}
		private CustomerDetails _customerIdSource = null;
		
		/// <summary>
		/// Gets or sets the source <see cref="CustomerDetails"/>.
		/// </summary>
		/// <value>The source CustomerDetails for CustomerId.</value>
		[XmlIgnore()]
		[Browsable(false)]
		public virtual CustomerDetails CustomerIdSource
      	{
            get { return this._customerIdSource; }
            set { this._customerIdSource = value; }
      	}
		#endregion
		#endregion Variable Declarations
	
		#region Data Properties

		#endregion Data Properties
		
		#region Clone Method

		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public Object Clone()
		{
			ClassArrangementEntityData _tmp = new ClassArrangementEntityData();
						
			_tmp.CustomerId = this.CustomerId;
			_tmp.OriginalCustomerId = this.OriginalCustomerId;
			_tmp.ClassId = this.ClassId;
			_tmp.OriginalClassId = this.OriginalClassId;
			_tmp.CreateDate = this.CreateDate;
			_tmp.OriginalCreateDate = this.OriginalCreateDate;
			
			
			#region Source Parent Composite Entities
			if (this.ClassIdSource != null)
				_tmp.ClassIdSource = MakeCopyOf(this.ClassIdSource) as ClassDetails;
			if (this.CustomerIdSource != null)
				_tmp.CustomerIdSource = MakeCopyOf(this.CustomerIdSource) as CustomerDetails;
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public object Clone(IDictionary existingCopies)
		{
			if (existingCopies == null)
				existingCopies = new Hashtable();
				
			ClassArrangementEntityData _tmp = new ClassArrangementEntityData();
						
			_tmp.CustomerId = this.CustomerId;
			_tmp.OriginalCustomerId = this.OriginalCustomerId;
			_tmp.ClassId = this.ClassId;
			_tmp.OriginalClassId = this.OriginalClassId;
			_tmp.CreateDate = this.CreateDate;
			_tmp.OriginalCreateDate = this.OriginalCreateDate;
			
			
			#region Source Parent Composite Entities
			if (this.ClassIdSource != null && existingCopies.Contains(this.ClassIdSource))
				_tmp.ClassIdSource = existingCopies[this.ClassIdSource] as ClassDetails;
			else
				_tmp.ClassIdSource = MakeCopyOf(this.ClassIdSource, existingCopies) as ClassDetails;
			if (this.CustomerIdSource != null && existingCopies.Contains(this.CustomerIdSource))
				_tmp.CustomerIdSource = existingCopies[this.CustomerIdSource] as CustomerDetails;
			else
				_tmp.CustomerIdSource = MakeCopyOf(this.CustomerIdSource, existingCopies) as CustomerDetails;
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		#endregion Clone Method
		
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public EntityState	EntityState
		{
			get { return currentEntityState;  }
			set { currentEntityState = value; }
		}
	
	}//End struct











		#endregion
		
				
		
		#region Events trigger
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="ClassArrangementColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanging(ClassArrangementColumn column)
		{
			OnColumnChanging(column, null);
			return;
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="ClassArrangementColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanged(ClassArrangementColumn column)
		{
			OnColumnChanged(column, null);
			return;
		} 
		
		
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="ClassArrangementColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanging(ClassArrangementColumn column, object value)
		{
			if(IsEntityTracked && EntityState != EntityState.Added && !EntityManager.TrackChangedEntities)
				EntityManager.StopTracking(entityTrackingKey);
				
			if (!SuppressEntityEvents)
			{
				ClassArrangementEventHandler handler = ColumnChanging;
				if(handler != null)
				{
					handler(this, new ClassArrangementEventArgs(column, value));
				}
			}
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="ClassArrangementColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanged(ClassArrangementColumn column, object value)
		{
			if (!SuppressEntityEvents)
			{
				ClassArrangementEventHandler handler = ColumnChanged;
				if(handler != null)
				{
					handler(this, new ClassArrangementEventArgs(column, value));
				}
			
				// warn the parent list that i have changed
				OnEntityChanged();
			}
		} 
		#endregion
			
	} // End Class
	
	
	#region ClassArrangementEventArgs class
	/// <summary>
	/// Provides data for the ColumnChanging and ColumnChanged events.
	/// </summary>
	/// <remarks>
	/// The ColumnChanging and ColumnChanged events occur when a change is made to the value 
	/// of a property of a <see cref="ClassArrangement"/> object.
	/// </remarks>
	public class ClassArrangementEventArgs : System.EventArgs
	{
		private ClassArrangementColumn column;
		private object value;
		
		///<summary>
		/// Initalizes a new Instance of the ClassArrangementEventArgs class.
		///</summary>
		public ClassArrangementEventArgs(ClassArrangementColumn column)
		{
			this.column = column;
		}
		
		///<summary>
		/// Initalizes a new Instance of the ClassArrangementEventArgs class.
		///</summary>
		public ClassArrangementEventArgs(ClassArrangementColumn column, object value)
		{
			this.column = column;
			this.value = value;
		}
		
		///<summary>
		/// The ClassArrangementColumn that was modified, which has raised the event.
		///</summary>
		///<value cref="ClassArrangementColumn" />
		public ClassArrangementColumn Column { get { return this.column; } }
		
		/// <summary>
        /// Gets the current value of the column.
        /// </summary>
        /// <value>The current value of the column.</value>
		public object Value{ get { return this.value; } }

	}
	#endregion
	
	///<summary>
	/// Define a delegate for all ClassArrangement related events.
	///</summary>
	public delegate void ClassArrangementEventHandler(object sender, ClassArrangementEventArgs e);
	
	#region ClassArrangementComparer
		
	/// <summary>
	///	Strongly Typed IComparer
	/// </summary>
	public class ClassArrangementComparer : System.Collections.Generic.IComparer<ClassArrangement>
	{
		ClassArrangementColumn whichComparison;
		
		/// <summary>
        /// Initializes a new instance of the <see cref="T:ClassArrangementComparer"/> class.
        /// </summary>
		public ClassArrangementComparer()
        {            
        }               
        
        /// <summary>
        /// Initializes a new instance of the <see cref="T:ClassArrangementComparer"/> class.
        /// </summary>
        /// <param name="column">The column to sort on.</param>
        public ClassArrangementComparer(ClassArrangementColumn column)
        {
            this.whichComparison = column;
        }

		/// <summary>
        /// Determines whether the specified <c cref="ClassArrangement"/> instances are considered equal.
        /// </summary>
        /// <param name="a">The first <c cref="ClassArrangement"/> to compare.</param>
        /// <param name="b">The second <c>ClassArrangement</c> to compare.</param>
        /// <returns>true if objA is the same instance as objB or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
        public bool Equals(ClassArrangement a, ClassArrangement b)
        {
            return this.Compare(a, b) == 0;
        }

		/// <summary>
        /// Gets the hash code of the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns></returns>
        public int GetHashCode(ClassArrangement entity)
        {
            return entity.GetHashCode();
        }

        /// <summary>
        /// Performs a case-insensitive comparison of two objects of the same type and returns a value indicating whether one is less than, equal to, or greater than the other.
        /// </summary>
        /// <param name="a">The first object to compare.</param>
        /// <param name="b">The second object to compare.</param>
        /// <returns></returns>
        public int Compare(ClassArrangement a, ClassArrangement b)
        {
        	EntityPropertyComparer entityPropertyComparer = new EntityPropertyComparer(this.whichComparison.ToString());
        	return entityPropertyComparer.Compare(a, b);
        }

		/// <summary>
        /// Gets or sets the column that will be used for comparison.
        /// </summary>
        /// <value>The comparison column.</value>
        public ClassArrangementColumn WhichComparison
        {
            get { return this.whichComparison; }
            set { this.whichComparison = value; }
        }
	}
	
	#endregion
	
	#region ClassArrangementKey Class

	/// <summary>
	/// Wraps the unique identifier values for the <see cref="ClassArrangement"/> object.
	/// </summary>
	[Serializable]
	[CLSCompliant(true)]
	public class ClassArrangementKey : EntityKeyBase
	{
		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the ClassArrangementKey class.
		/// </summary>
		public ClassArrangementKey()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the ClassArrangementKey class.
		/// </summary>
		public ClassArrangementKey(ClassArrangementBase entity)
		{
			this.Entity = entity;

			#region Init Properties

			if ( entity != null )
			{
				this.CustomerId = entity.CustomerId;
				this.ClassId = entity.ClassId;
				this.CreateDate = entity.CreateDate;
			}

			#endregion
		}
		
		/// <summary>
		/// Initializes a new instance of the ClassArrangementKey class.
		/// </summary>
		public ClassArrangementKey(System.Int32 _customerId, System.Int32 _classId, System.DateTime _createDate)
		{
			#region Init Properties

			this.CustomerId = _customerId;
			this.ClassId = _classId;
			this.CreateDate = _createDate;

			#endregion
		}
		
		#endregion Constructors

		#region Properties
		
		// member variable for the Entity property
		private ClassArrangementBase _entity;
		
		/// <summary>
		/// Gets or sets the Entity property.
		/// </summary>
		public ClassArrangementBase Entity
		{
			get { return _entity; }
			set { _entity = value; }
		}
		
		// member variable for the CustomerId property
		private System.Int32 _customerId;
		
		/// <summary>
		/// Gets or sets the CustomerId property.
		/// </summary>
		public System.Int32 CustomerId
		{
			get { return _customerId; }
			set
			{
				if ( this.Entity != null )
					this.Entity.CustomerId = value;
				
				_customerId = value;
			}
		}
		
		// member variable for the ClassId property
		private System.Int32 _classId;
		
		/// <summary>
		/// Gets or sets the ClassId property.
		/// </summary>
		public System.Int32 ClassId
		{
			get { return _classId; }
			set
			{
				if ( this.Entity != null )
					this.Entity.ClassId = value;
				
				_classId = value;
			}
		}
		
		// member variable for the CreateDate property
		private System.DateTime _createDate;
		
		/// <summary>
		/// Gets or sets the CreateDate property.
		/// </summary>
		public System.DateTime CreateDate
		{
			get { return _createDate; }
			set
			{
				if ( this.Entity != null )
					this.Entity.CreateDate = value;
				
				_createDate = value;
			}
		}
		
		#endregion

		#region Methods
		
		/// <summary>
		/// Reads values from the supplied <see cref="IDictionary"/> object into
		/// properties of the current object.
		/// </summary>
		/// <param name="values">An <see cref="IDictionary"/> instance that contains
		/// the key/value pairs to be used as property values.</param>
		public override void Load(IDictionary values)
		{
			#region Init Properties

			if ( values != null )
			{
				CustomerId = ( values["CustomerId"] != null ) ? (System.Int32) EntityUtil.ChangeType(values["CustomerId"], typeof(System.Int32)) : (int)0;
				ClassId = ( values["ClassId"] != null ) ? (System.Int32) EntityUtil.ChangeType(values["ClassId"], typeof(System.Int32)) : (int)0;
				CreateDate = ( values["CreateDate"] != null ) ? (System.DateTime) EntityUtil.ChangeType(values["CreateDate"], typeof(System.DateTime)) : DateTime.MinValue;
			}

			#endregion
		}

		/// <summary>
		/// Creates a new <see cref="IDictionary"/> object and populates it
		/// with the property values of the current object.
		/// </summary>
		/// <returns>A collection of name/value pairs.</returns>
		public override IDictionary ToDictionary()
		{
			IDictionary values = new Hashtable();

			#region Init Dictionary

			values.Add("CustomerId", CustomerId);
			values.Add("ClassId", ClassId);
			values.Add("CreateDate", CreateDate);

			#endregion Init Dictionary

			return values;
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return String.Format("CustomerId: {0}{3}ClassId: {1}{3}CreateDate: {2}{3}",
								CustomerId,
								ClassId,
								CreateDate,
								System.Environment.NewLine);
		}

		#endregion Methods
	}
	
	#endregion	

	#region ClassArrangementColumn Enum
	
	/// <summary>
	/// Enumerate the ClassArrangement columns.
	/// </summary>
	[Serializable]
	public enum ClassArrangementColumn : int
	{
		/// <summary>
		/// CustomerId : 
		/// </summary>
		[EnumTextValue("CustomerId")]
		[ColumnEnum("CustomerId", typeof(System.Int32), System.Data.DbType.Int32, true, false, false)]
		CustomerId = 1,
		/// <summary>
		/// ClassId : 
		/// </summary>
		[EnumTextValue("ClassId")]
		[ColumnEnum("ClassId", typeof(System.Int32), System.Data.DbType.Int32, true, false, false)]
		ClassId = 2,
		/// <summary>
		/// CreateDate : 
		/// </summary>
		[EnumTextValue("CreateDate")]
		[ColumnEnum("CreateDate", typeof(System.DateTime), System.Data.DbType.DateTime, true, false, false)]
		CreateDate = 3
	}//End enum

	#endregion ClassArrangementColumn Enum

} // end namespace
