
/*
	File generated by NetTiers templates [www.nettiers.com]
	Important: Do not modify this file. Edit the file ClassDetails.cs instead.
*/

#region using directives
using System;
using System.ComponentModel;
using System.Collections;
using System.Xml.Serialization;
using System.Runtime.Serialization;

using AIProject.Entities.Validation;
#endregion

namespace AIProject.Entities
{
	///<summary>
	/// An object representation of the 'ClassDetails' table. [No description found the database]	
	///</summary>
	[Serializable]
	[DataObject, CLSCompliant(true)]
	public abstract partial class ClassDetailsBase : EntityBase, IClassDetails, IEntityId<ClassDetailsKey>, System.IComparable, System.ICloneable, ICloneableEx, IEditableObject, IComponent, INotifyPropertyChanged
	{		
		#region Variable Declarations
		
		/// <summary>
		///  Hold the inner data of the entity.
		/// </summary>
		private ClassDetailsEntityData entityData;
		
		/// <summary>
		/// 	Hold the original data of the entity, as loaded from the repository.
		/// </summary>
		private ClassDetailsEntityData _originalData;
		
		/// <summary>
		/// 	Hold a backup of the inner data of the entity.
		/// </summary>
		private ClassDetailsEntityData backupData; 
		
		/// <summary>
		/// 	Key used if Tracking is Enabled for the <see cref="EntityLocator" />.
		/// </summary>
		private string entityTrackingKey;
		
		/// <summary>
		/// 	Hold the parent TList&lt;entity&gt; in which this entity maybe contained.
		/// </summary>
		/// <remark>Mostly used for databinding</remark>
		[NonSerialized]
		private TList<ClassDetails> parentCollection;
		
		private bool inTxn = false;
		
		/// <summary>
		/// Occurs when a value is being changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event ClassDetailsEventHandler ColumnChanging;		
		
		/// <summary>
		/// Occurs after a value has been changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event ClassDetailsEventHandler ColumnChanged;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="ClassDetailsBase"/> instance.
		///</summary>
		public ClassDetailsBase()
		{
			this.entityData = new ClassDetailsEntityData();
			this.backupData = null;
		}		
		
		///<summary>
		/// Creates a new <see cref="ClassDetailsBase"/> instance.
		///</summary>
		///<param name="_classId"></param>
		///<param name="_className"></param>
		///<param name="_classTime"></param>
		///<param name="_courseId"></param>
		///<param name="_teacherId"></param>
		public ClassDetailsBase(System.Int32 _classId, System.String _className, System.Int32? _classTime, 
			System.Int32? _courseId, System.Int32? _teacherId)
		{
			this.entityData = new ClassDetailsEntityData();
			this.backupData = null;

			this.ClassId = _classId;
			this.ClassName = _className;
			this.ClassTime = _classTime;
			this.CourseId = _courseId;
			this.TeacherId = _teacherId;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="ClassDetails"/> instance.
		///</summary>
		///<param name="_classId"></param>
		///<param name="_className"></param>
		///<param name="_classTime"></param>
		///<param name="_courseId"></param>
		///<param name="_teacherId"></param>
		public static ClassDetails CreateClassDetails(System.Int32 _classId, System.String _className, System.Int32? _classTime, 
			System.Int32? _courseId, System.Int32? _teacherId)
		{
			ClassDetails newClassDetails = new ClassDetails();
			newClassDetails.ClassId = _classId;
			newClassDetails.ClassName = _className;
			newClassDetails.ClassTime = _classTime;
			newClassDetails.CourseId = _courseId;
			newClassDetails.TeacherId = _teacherId;
			return newClassDetails;
		}
				
		#endregion Constructors
			
		#region Properties	
		
		#region Data Properties		
		/// <summary>
		/// 	Gets or sets the ClassId property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, false, false)]
		public virtual System.Int32 ClassId
		{
			get
			{
				return this.entityData.ClassId; 
			}
			
			set
			{
				if (this.entityData.ClassId == value)
					return;
					
				OnColumnChanging(ClassDetailsColumn.ClassId, this.entityData.ClassId);
				this.entityData.ClassId = value;
				this.EntityId.ClassId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(ClassDetailsColumn.ClassId, this.entityData.ClassId);
				OnPropertyChanged("ClassId");
			}
		}
		
		/// <summary>
		/// 	Get the original value of the ClassId property.
		///		
		/// </summary>
		/// <remarks>This is the original value of the ClassId property.</remarks>
		/// <value>This type is int</value>
		[BrowsableAttribute(false)/*, XmlIgnoreAttribute()*/]
		public  virtual System.Int32 OriginalClassId
		{
			get { return this.entityData.OriginalClassId; }
			set { this.entityData.OriginalClassId = value; }
		}
		
		/// <summary>
		/// 	Gets or sets the ClassName property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 50)]
		public virtual System.String ClassName
		{
			get
			{
				return this.entityData.ClassName; 
			}
			
			set
			{
				if (this.entityData.ClassName == value)
					return;
					
				OnColumnChanging(ClassDetailsColumn.ClassName, this.entityData.ClassName);
				this.entityData.ClassName = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(ClassDetailsColumn.ClassName, this.entityData.ClassName);
				OnPropertyChanged("ClassName");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the ClassTime property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return (int)0. It is up to the developer
		/// to check the value of IsClassTimeNull() and perform business logic appropriately.
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Int32? ClassTime
		{
			get
			{
				return this.entityData.ClassTime; 
			}
			
			set
			{
				if (this.entityData.ClassTime == value)
					return;
					
				OnColumnChanging(ClassDetailsColumn.ClassTime, this.entityData.ClassTime);
				this.entityData.ClassTime = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(ClassDetailsColumn.ClassTime, this.entityData.ClassTime);
				OnPropertyChanged("ClassTime");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the CourseId property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return (int)0. It is up to the developer
		/// to check the value of IsCourseIdNull() and perform business logic appropriately.
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Int32? CourseId
		{
			get
			{
				return this.entityData.CourseId; 
			}
			
			set
			{
				if (this.entityData.CourseId == value)
					return;
					
				OnColumnChanging(ClassDetailsColumn.CourseId, this.entityData.CourseId);
				this.entityData.CourseId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(ClassDetailsColumn.CourseId, this.entityData.CourseId);
				OnPropertyChanged("CourseId");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the TeacherId property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return (int)0. It is up to the developer
		/// to check the value of IsTeacherIdNull() and perform business logic appropriately.
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Int32? TeacherId
		{
			get
			{
				return this.entityData.TeacherId; 
			}
			
			set
			{
				if (this.entityData.TeacherId == value)
					return;
					
				OnColumnChanging(ClassDetailsColumn.TeacherId, this.entityData.TeacherId);
				this.entityData.TeacherId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(ClassDetailsColumn.TeacherId, this.entityData.TeacherId);
				OnPropertyChanged("TeacherId");
			}
		}
		
		#endregion Data Properties		

		#region Source Foreign Key Property
				
		/// <summary>
		/// Gets or sets the source <see cref="ClassTime"/>.
		/// </summary>
		/// <value>The source ClassTime for ClassTime.</value>
        [XmlIgnore()]
		[Browsable(false), System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual ClassTime ClassTimeSource
      	{
            get { return entityData.ClassTimeSource; }
            set { entityData.ClassTimeSource = value; }
      	}
		/// <summary>
		/// Gets or sets the source <see cref="CourseDetails"/>.
		/// </summary>
		/// <value>The source CourseDetails for CourseId.</value>
        [XmlIgnore()]
		[Browsable(false), System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual CourseDetails CourseIdSource
      	{
            get { return entityData.CourseIdSource; }
            set { entityData.CourseIdSource = value; }
      	}
		/// <summary>
		/// Gets or sets the source <see cref="TeacherDetails"/>.
		/// </summary>
		/// <value>The source TeacherDetails for TeacherId.</value>
        [XmlIgnore()]
		[Browsable(false), System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual TeacherDetails TeacherIdSource
      	{
            get { return entityData.TeacherIdSource; }
            set { entityData.TeacherIdSource = value; }
      	}
		#endregion
		
		#region Children Collections
	
		/// <summary>
		///	Holds a collection of ClassArrangement objects
		///	which are related to this object through the relation FK_ClassArrangement_ClassDetails
		/// </summary>	
		[System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual TList<ClassArrangement> ClassArrangementCollection
		{
			get { return entityData.ClassArrangementCollection; }
			set { entityData.ClassArrangementCollection = value; }	
		}
		#endregion Children Collections
		
		#endregion
		#region Validation
		
		/// <summary>
		/// Assigns validation rules to this object based on model definition.
		/// </summary>
		/// <remarks>This method overrides the base class to add schema related validation.</remarks>
		protected override void AddValidationRules()
		{
			//Validation rules based on database schema.
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("ClassName", "Class Name", 50));
		}
   		#endregion
		
		#region Table Meta Data
		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string TableName
		{
			get { return "ClassDetails"; }
		}
		
		/// <summary>
		///		The name of the underlying database table's columns.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string[] TableColumns
		{
			get
			{
				return new string[] {"ClassId", "ClassName", "ClassTime", "CourseId", "TeacherId"};
			}
		}
		#endregion 
		
		#region IEditableObject
		
		#region  CancelAddNew Event
		/// <summary>
        /// The delegate for the CancelAddNew event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		public delegate void CancelAddNewEventHandler(object sender, EventArgs e);
    
    	/// <summary>
		/// The CancelAddNew event.
		/// </summary>
		[field:NonSerialized]
		public event CancelAddNewEventHandler CancelAddNew ;

		/// <summary>
        /// Called when [cancel add new].
        /// </summary>
        public void OnCancelAddNew()
        {    
			if (!SuppressEntityEvents)
			{
	            CancelAddNewEventHandler handler = CancelAddNew ;
            	if (handler != null)
	            {    
    	            handler(this, EventArgs.Empty) ;
        	    }
	        }
        }
		#endregion 
		
		/// <summary>
		/// Begins an edit on an object.
		/// </summary>
		void IEditableObject.BeginEdit() 
	    {
	        //Console.WriteLine("Start BeginEdit");
	        if (!inTxn) 
	        {
	            this.backupData = this.entityData.Clone() as ClassDetailsEntityData;
	            inTxn = true;
	            //Console.WriteLine("BeginEdit");
	        }
	        //Console.WriteLine("End BeginEdit");
	    }
	
		/// <summary>
		/// Discards changes since the last <c>BeginEdit</c> call.
		/// </summary>
	    void IEditableObject.CancelEdit() 
	    {
	        //Console.WriteLine("Start CancelEdit");
	        if (this.inTxn) 
	        {
	            this.entityData = this.backupData;
	            this.backupData = null;
				this.inTxn = false;

				if (this.bindingIsNew)
	        	//if (this.EntityState == EntityState.Added)
	        	{
					if (this.parentCollection != null)
						this.parentCollection.Remove( (ClassDetails) this ) ;
				}	            
	        }
	        //Console.WriteLine("End CancelEdit");
	    }
	
		/// <summary>
		/// Pushes changes since the last <c>BeginEdit</c> or <c>IBindingList.AddNew</c> call into the underlying object.
		/// </summary>
	    void IEditableObject.EndEdit() 
	    {
	        //Console.WriteLine("Start EndEdit" + this.custData.id + this.custData.lastName);
	        if (this.inTxn) 
	        {
	            this.backupData = null;
				if (this.IsDirty) 
				{
					if (this.bindingIsNew) {
						this.EntityState = EntityState.Added;
						this.bindingIsNew = false ;
					}
					else
						if (this.EntityState == EntityState.Unchanged) 
							this.EntityState = EntityState.Changed ;
				}

				this.bindingIsNew = false ;
	            this.inTxn = false;	            
	        }
	        //Console.WriteLine("End EndEdit");
	    }
	    
	    /// <summary>
        /// Gets or sets the parent collection of this current entity, if available.
        /// </summary>
        /// <value>The parent collection.</value>
	    [XmlIgnore]
		[Browsable(false)]
	    public override object ParentCollection
	    {
	        get 
	        {
	            return this.parentCollection;
	        }
	        set 
	        {
	            this.parentCollection = value as TList<ClassDetails>;
	        }
	    }
	    
	    /// <summary>
        /// Called when the entity is changed.
        /// </summary>
	    private void OnEntityChanged() 
	    {
	        if (!SuppressEntityEvents && !inTxn && this.parentCollection != null) 
	        {
	            this.parentCollection.EntityChanged(this as ClassDetails);
	        }
	    }


		#endregion
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed ClassDetails Entity 
		///</summary>
		protected virtual ClassDetails Copy(IDictionary existingCopies)
		{
			if (existingCopies == null)
			{
				// This is the root of the tree to be copied!
				existingCopies = new Hashtable();
			}

			//shallow copy entity
			ClassDetails copy = new ClassDetails();
			existingCopies.Add(this, copy);
			copy.SuppressEntityEvents = true;
				copy.ClassId = this.ClassId;
					copy.OriginalClassId = this.OriginalClassId;
				copy.ClassName = this.ClassName;
				copy.ClassTime = this.ClassTime;
				copy.CourseId = this.CourseId;
				copy.TeacherId = this.TeacherId;
			
			if (this.ClassTimeSource != null && existingCopies.Contains(this.ClassTimeSource))
				copy.ClassTimeSource = existingCopies[this.ClassTimeSource] as ClassTime;
			else
				copy.ClassTimeSource = MakeCopyOf(this.ClassTimeSource, existingCopies) as ClassTime;
			if (this.CourseIdSource != null && existingCopies.Contains(this.CourseIdSource))
				copy.CourseIdSource = existingCopies[this.CourseIdSource] as CourseDetails;
			else
				copy.CourseIdSource = MakeCopyOf(this.CourseIdSource, existingCopies) as CourseDetails;
			if (this.TeacherIdSource != null && existingCopies.Contains(this.TeacherIdSource))
				copy.TeacherIdSource = existingCopies[this.TeacherIdSource] as TeacherDetails;
			else
				copy.TeacherIdSource = MakeCopyOf(this.TeacherIdSource, existingCopies) as TeacherDetails;
		
			//deep copy nested objects
			copy.ClassArrangementCollection = (TList<ClassArrangement>) MakeCopyOf(this.ClassArrangementCollection, existingCopies); 
			copy.EntityState = this.EntityState;
			copy.SuppressEntityEvents = false;
			return copy;
		}		
		
		
		
		///<summary>
		///  Returns a Typed ClassDetails Entity 
		///</summary>
		public virtual ClassDetails Copy()
		{
			return this.Copy(null);	
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone()
		{
			return this.Copy(null);
		}
		
		///<summary>
		/// ICloneableEx.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone(IDictionary existingCopies)
		{
			return this.Copy(existingCopies);
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x == null)
				return null;
				
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x, IDictionary existingCopies)
		{
			if (x == null)
				return null;
			
			if (x is ICloneableEx)
			{
				// Return a deep copy of the object
				return ((ICloneableEx)x).Clone(existingCopies);
			}
			else if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable or IClonableEx Interface.");
		}
		
		
		///<summary>
		///  Returns a Typed ClassDetails Entity which is a deep copy of the current entity.
		///</summary>
		public virtual ClassDetails DeepCopy()
		{
			return EntityHelper.Clone<ClassDetails>(this as ClassDetails);	
		}
		#endregion
		
		#region Methods	
			
		///<summary>
		/// Revert all changes and restore original values.
		///</summary>
		public override void CancelChanges()
		{
			IEditableObject obj = (IEditableObject) this;
			obj.CancelEdit();

			this.entityData = null;
			if (this._originalData != null)
			{
				this.entityData = this._originalData.Clone() as ClassDetailsEntityData;
			}
			else
			{
				//Since this had no _originalData, then just reset the entityData with a new one.  entityData cannot be null.
				this.entityData = new ClassDetailsEntityData();
			}
		}	
		
		/// <summary>
		/// Accepts the changes made to this object.
		/// </summary>
		/// <remarks>
		/// After calling this method, properties: IsDirty, IsNew are false. IsDeleted flag remains unchanged as it is handled by the parent List.
		/// </remarks>
		public override void AcceptChanges()
		{
			base.AcceptChanges();

			// we keep of the original version of the data
			this._originalData = null;
			this._originalData = this.entityData.Clone() as ClassDetailsEntityData;
		}
		
		#region Comparision with original data
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="column">The column.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool IsPropertyChanged(ClassDetailsColumn column)
		{
			switch(column)
			{
					case ClassDetailsColumn.ClassId:
					return entityData.ClassId != _originalData.ClassId;
					case ClassDetailsColumn.ClassName:
					return entityData.ClassName != _originalData.ClassName;
					case ClassDetailsColumn.ClassTime:
					return entityData.ClassTime != _originalData.ClassTime;
					case ClassDetailsColumn.CourseId:
					return entityData.CourseId != _originalData.CourseId;
					case ClassDetailsColumn.TeacherId:
					return entityData.TeacherId != _originalData.TeacherId;
			
				default:
					return false;
			}
		}
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="columnName">The column name.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public override bool IsPropertyChanged(string columnName)
		{
			return 	IsPropertyChanged(EntityHelper.GetEnumValue< ClassDetailsColumn >(columnName));
		}
		
		/// <summary>
		/// Determines whether the data has changed from original.
		/// </summary>
		/// <returns>
		/// 	<c>true</c> if data has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool HasDataChanged()
		{
			bool result = false;
			result = result || entityData.ClassId != _originalData.ClassId;
			result = result || entityData.ClassName != _originalData.ClassName;
			result = result || entityData.ClassTime != _originalData.ClassTime;
			result = result || entityData.CourseId != _originalData.CourseId;
			result = result || entityData.TeacherId != _originalData.TeacherId;
			return result;
		}	
		
		///<summary>
		///  Returns a ClassDetails Entity with the original data.
		///</summary>
		public ClassDetails GetOriginalEntity()
		{
			if (_originalData != null)
				return CreateClassDetails(
				_originalData.ClassId,
				_originalData.ClassName,
				_originalData.ClassTime,
				_originalData.CourseId,
				_originalData.TeacherId
				);
				
			return (ClassDetails)this.Clone();
		}
		#endregion
	
	#region Value Semantics Instance Equality
        ///<summary>
        /// Returns a value indicating whether this instance is equal to a specified object using value semantics.
        ///</summary>
        ///<param name="Object1">An object to compare to this instance.</param>
        ///<returns>true if Object1 is a <see cref="ClassDetailsBase"/> and has the same value as this instance; otherwise, false.</returns>
        public override bool Equals(object Object1)
        {
			// Cast exception if Object1 is null or DbNull
			if (Object1 != null && Object1 != DBNull.Value && Object1 is ClassDetailsBase)
				return ValueEquals(this, (ClassDetailsBase)Object1);
			else
				return false;
        }

        /// <summary>
		/// Serves as a hash function for a particular type, suitable for use in hashing algorithms and data structures like a hash table.
        /// Provides a hash function that is appropriate for <see cref="ClassDetailsBase"/> class 
        /// and that ensures a better distribution in the hash table
        /// </summary>
        /// <returns>number (hash code) that corresponds to the value of an object</returns>
        public override int GetHashCode()
        {
			return this.ClassId.GetHashCode() ^ 
					((this.ClassName == null) ? string.Empty : this.ClassName.ToString()).GetHashCode() ^ 
					((this.ClassTime == null) ? string.Empty : this.ClassTime.ToString()).GetHashCode() ^ 
					((this.CourseId == null) ? string.Empty : this.CourseId.ToString()).GetHashCode() ^ 
					((this.TeacherId == null) ? string.Empty : this.TeacherId.ToString()).GetHashCode();
        }
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object using value semantics.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="ClassDetailsBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(ClassDetailsBase toObject)
		{
			if (toObject == null)
				return false;
			return ValueEquals(this, toObject);
		}
		#endregion
		
		///<summary>
		/// Determines whether the specified <see cref="ClassDetailsBase"/> instances are considered equal using value semantics.
		///</summary>
		///<param name="Object1">The first <see cref="ClassDetailsBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="ClassDetailsBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool ValueEquals(ClassDetailsBase Object1, ClassDetailsBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;
				
			bool equal = true;
			if (Object1.ClassId != Object2.ClassId)
				equal = false;
			if ( Object1.ClassName != null && Object2.ClassName != null )
			{
				if (Object1.ClassName != Object2.ClassName)
					equal = false;
			}
			else if (Object1.ClassName == null ^ Object2.ClassName == null )
			{
				equal = false;
			}
			if ( Object1.ClassTime != null && Object2.ClassTime != null )
			{
				if (Object1.ClassTime != Object2.ClassTime)
					equal = false;
			}
			else if (Object1.ClassTime == null ^ Object2.ClassTime == null )
			{
				equal = false;
			}
			if ( Object1.CourseId != null && Object2.CourseId != null )
			{
				if (Object1.CourseId != Object2.CourseId)
					equal = false;
			}
			else if (Object1.CourseId == null ^ Object2.CourseId == null )
			{
				equal = false;
			}
			if ( Object1.TeacherId != null && Object2.TeacherId != null )
			{
				if (Object1.TeacherId != Object2.TeacherId)
					equal = false;
			}
			else if (Object1.TeacherId == null ^ Object2.TeacherId == null )
			{
				equal = false;
			}
					
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
			//return this. GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]) .CompareTo(((ClassDetailsBase)obj).GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]));
		}
		
		/*
		// static method to get a Comparer object
        public static ClassDetailsComparer GetComparer()
        {
            return new ClassDetailsComparer();
        }
        */

        // Comparer delegates back to ClassDetails
        // Employee uses the integer's default
        // CompareTo method
        /*
        public int CompareTo(Item rhs)
        {
            return this.Id.CompareTo(rhs.Id);
        }
        */

/*
        // Special implementation to be called by custom comparer
        public int CompareTo(ClassDetails rhs, ClassDetailsColumn which)
        {
            switch (which)
            {
            	
            	
            	case ClassDetailsColumn.ClassId:
            		return this.ClassId.CompareTo(rhs.ClassId);
            		
            		                 
            	
            	
            	case ClassDetailsColumn.ClassName:
            		return this.ClassName.CompareTo(rhs.ClassName);
            		
            		                 
            	
            	
            	case ClassDetailsColumn.ClassTime:
            		return this.ClassTime.Value.CompareTo(rhs.ClassTime.Value);
            		
            		                 
            	
            	
            	case ClassDetailsColumn.CourseId:
            		return this.CourseId.Value.CompareTo(rhs.CourseId.Value);
            		
            		                 
            	
            	
            	case ClassDetailsColumn.TeacherId:
            		return this.TeacherId.Value.CompareTo(rhs.TeacherId.Value);
            		
            		                 
            }
            return 0;
        }
        */
	
		#endregion
		
		#region IComponent Members
		
		private ISite _site = null;

		/// <summary>
		/// Gets or Sets the site where this data is located.
		/// </summary>
		[XmlIgnore]
		[SoapIgnore]
		[Browsable(false)]
		public ISite Site
		{
			get{ return this._site; }
			set{ this._site = value; }
		}

		#endregion

		#region IDisposable Members
		
		/// <summary>
		/// Notify those that care when we dispose.
		/// </summary>
		[field:NonSerialized]
		public event System.EventHandler Disposed;

		/// <summary>
		/// Clean up. Nothing here though.
		/// </summary>
		public virtual void Dispose()
		{
			this.parentCollection = null;
			this.Dispose(true);
			GC.SuppressFinalize(this);
		}
		
		/// <summary>
		/// Clean up.
		/// </summary>
		protected virtual void Dispose(bool disposing)
		{
			if (disposing)
			{
				EventHandler handler = Disposed;
				if (handler != null)
					handler(this, EventArgs.Empty);
			}
		}
		
		#endregion
				
		#region IEntityKey<ClassDetailsKey> Members
		
		// member variable for the EntityId property
		private ClassDetailsKey _entityId;

		/// <summary>
		/// Gets or sets the EntityId property.
		/// </summary>
		[XmlIgnore]
		public virtual ClassDetailsKey EntityId
		{
			get
			{
				if ( _entityId == null )
				{
					_entityId = new ClassDetailsKey(this);
				}

				return _entityId;
			}
			set
			{
				if ( value != null )
				{
					value.Entity = this;
				}
				
				_entityId = value;
			}
		}
		
		#endregion
		
		#region EntityState
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false) , XmlIgnoreAttribute()]
		public override EntityState EntityState 
		{ 
			get{ return entityData.EntityState;	 } 
			set{ entityData.EntityState = value; } 
		}
		#endregion 
		
		#region EntityTrackingKey
		///<summary>
		/// Provides the tracking key for the <see cref="EntityLocator"/>
		///</summary>
		[XmlIgnore]
		public override string EntityTrackingKey
		{
			get
			{
				if(entityTrackingKey == null)
					entityTrackingKey = new System.Text.StringBuilder("ClassDetails")
					.Append("|").Append( this.ClassId.ToString()).ToString();
				return entityTrackingKey;
			}
			set
		    {
		        if (value != null)
                    entityTrackingKey = value;
		    }
		}
		#endregion 
		
		#region ToString Method
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{6}{5}- ClassId: {0}{5}- ClassName: {1}{5}- ClassTime: {2}{5}- CourseId: {3}{5}- TeacherId: {4}{5}{7}", 
				this.ClassId,
				(this.ClassName == null) ? string.Empty : this.ClassName.ToString(),
				(this.ClassTime == null) ? string.Empty : this.ClassTime.ToString(),
				(this.CourseId == null) ? string.Empty : this.CourseId.ToString(),
				(this.TeacherId == null) ? string.Empty : this.TeacherId.ToString(),
				System.Environment.NewLine, 
				this.GetType(),
				this.Error.Length == 0 ? string.Empty : string.Format("- Error: {0}\n",this.Error));
		}
		
		#endregion ToString Method
		
		#region Inner data class
		
	/// <summary>
	///		The data structure representation of the 'ClassDetails' table.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Serializable]
	internal protected class ClassDetailsEntityData : ICloneable, ICloneableEx
	{
		#region Variable Declarations
		private EntityState currentEntityState = EntityState.Added;
		
		#region Primary key(s)
		/// <summary>			
		/// ClassId : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "ClassDetails"</remarks>
		public System.Int32 ClassId;
			
		/// <summary>
		/// keep a copy of the original so it can be used for editable primary keys.
		/// </summary>
		public System.Int32 OriginalClassId;
		
		#endregion
		
		#region Non Primary key(s)
		
		
		/// <summary>
		/// ClassName : 
		/// </summary>
		public System.String		  ClassName = null;
		
		/// <summary>
		/// ClassTime : 
		/// </summary>
		public System.Int32?		  ClassTime = null;
		
		/// <summary>
		/// CourseId : 
		/// </summary>
		public System.Int32?		  CourseId = null;
		
		/// <summary>
		/// TeacherId : 
		/// </summary>
		public System.Int32?		  TeacherId = null;
		#endregion
			
		#region Source Foreign Key Property
				
		private ClassTime _classTimeSource = null;
		
		/// <summary>
		/// Gets or sets the source <see cref="ClassTime"/>.
		/// </summary>
		/// <value>The source ClassTime for ClassTime.</value>
		[XmlIgnore()]
		[Browsable(false)]
		public virtual ClassTime ClassTimeSource
      	{
            get { return this._classTimeSource; }
            set { this._classTimeSource = value; }
      	}
		private CourseDetails _courseIdSource = null;
		
		/// <summary>
		/// Gets or sets the source <see cref="CourseDetails"/>.
		/// </summary>
		/// <value>The source CourseDetails for CourseId.</value>
		[XmlIgnore()]
		[Browsable(false)]
		public virtual CourseDetails CourseIdSource
      	{
            get { return this._courseIdSource; }
            set { this._courseIdSource = value; }
      	}
		private TeacherDetails _teacherIdSource = null;
		
		/// <summary>
		/// Gets or sets the source <see cref="TeacherDetails"/>.
		/// </summary>
		/// <value>The source TeacherDetails for TeacherId.</value>
		[XmlIgnore()]
		[Browsable(false)]
		public virtual TeacherDetails TeacherIdSource
      	{
            get { return this._teacherIdSource; }
            set { this._teacherIdSource = value; }
      	}
		#endregion
		#endregion Variable Declarations
	
		#region Data Properties

		#region ClassArrangementCollection
		
		private TList<ClassArrangement> _classArrangementClassId;
		
		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation _classArrangementClassId
		/// </summary>
		
		public TList<ClassArrangement> ClassArrangementCollection
		{
			get
			{
				if (_classArrangementClassId == null)
				{
				_classArrangementClassId = new TList<ClassArrangement>();
				}
	
				return _classArrangementClassId;
			}
			set { _classArrangementClassId = value; }
		}
		
		#endregion

		#endregion Data Properties
		
		#region Clone Method

		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public Object Clone()
		{
			ClassDetailsEntityData _tmp = new ClassDetailsEntityData();
						
			_tmp.ClassId = this.ClassId;
			_tmp.OriginalClassId = this.OriginalClassId;
			
			_tmp.ClassName = this.ClassName;
			_tmp.ClassTime = this.ClassTime;
			_tmp.CourseId = this.CourseId;
			_tmp.TeacherId = this.TeacherId;
			
			#region Source Parent Composite Entities
			if (this.ClassTimeSource != null)
				_tmp.ClassTimeSource = MakeCopyOf(this.ClassTimeSource) as ClassTime;
			if (this.CourseIdSource != null)
				_tmp.CourseIdSource = MakeCopyOf(this.CourseIdSource) as CourseDetails;
			if (this.TeacherIdSource != null)
				_tmp.TeacherIdSource = MakeCopyOf(this.TeacherIdSource) as TeacherDetails;
			#endregion
		
			#region Child Collections
			//deep copy nested objects
			if (this._classArrangementClassId != null)
				_tmp.ClassArrangementCollection = (TList<ClassArrangement>) MakeCopyOf(this.ClassArrangementCollection); 
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public object Clone(IDictionary existingCopies)
		{
			if (existingCopies == null)
				existingCopies = new Hashtable();
				
			ClassDetailsEntityData _tmp = new ClassDetailsEntityData();
						
			_tmp.ClassId = this.ClassId;
			_tmp.OriginalClassId = this.OriginalClassId;
			
			_tmp.ClassName = this.ClassName;
			_tmp.ClassTime = this.ClassTime;
			_tmp.CourseId = this.CourseId;
			_tmp.TeacherId = this.TeacherId;
			
			#region Source Parent Composite Entities
			if (this.ClassTimeSource != null && existingCopies.Contains(this.ClassTimeSource))
				_tmp.ClassTimeSource = existingCopies[this.ClassTimeSource] as ClassTime;
			else
				_tmp.ClassTimeSource = MakeCopyOf(this.ClassTimeSource, existingCopies) as ClassTime;
			if (this.CourseIdSource != null && existingCopies.Contains(this.CourseIdSource))
				_tmp.CourseIdSource = existingCopies[this.CourseIdSource] as CourseDetails;
			else
				_tmp.CourseIdSource = MakeCopyOf(this.CourseIdSource, existingCopies) as CourseDetails;
			if (this.TeacherIdSource != null && existingCopies.Contains(this.TeacherIdSource))
				_tmp.TeacherIdSource = existingCopies[this.TeacherIdSource] as TeacherDetails;
			else
				_tmp.TeacherIdSource = MakeCopyOf(this.TeacherIdSource, existingCopies) as TeacherDetails;
			#endregion
		
			#region Child Collections
			//deep copy nested objects
			_tmp.ClassArrangementCollection = (TList<ClassArrangement>) MakeCopyOf(this.ClassArrangementCollection, existingCopies); 
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		#endregion Clone Method
		
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public EntityState	EntityState
		{
			get { return currentEntityState;  }
			set { currentEntityState = value; }
		}
	
	}//End struct











		#endregion
		
				
		
		#region Events trigger
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="ClassDetailsColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanging(ClassDetailsColumn column)
		{
			OnColumnChanging(column, null);
			return;
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="ClassDetailsColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanged(ClassDetailsColumn column)
		{
			OnColumnChanged(column, null);
			return;
		} 
		
		
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="ClassDetailsColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanging(ClassDetailsColumn column, object value)
		{
			if(IsEntityTracked && EntityState != EntityState.Added && !EntityManager.TrackChangedEntities)
				EntityManager.StopTracking(entityTrackingKey);
				
			if (!SuppressEntityEvents)
			{
				ClassDetailsEventHandler handler = ColumnChanging;
				if(handler != null)
				{
					handler(this, new ClassDetailsEventArgs(column, value));
				}
			}
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="ClassDetailsColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanged(ClassDetailsColumn column, object value)
		{
			if (!SuppressEntityEvents)
			{
				ClassDetailsEventHandler handler = ColumnChanged;
				if(handler != null)
				{
					handler(this, new ClassDetailsEventArgs(column, value));
				}
			
				// warn the parent list that i have changed
				OnEntityChanged();
			}
		} 
		#endregion
			
	} // End Class
	
	
	#region ClassDetailsEventArgs class
	/// <summary>
	/// Provides data for the ColumnChanging and ColumnChanged events.
	/// </summary>
	/// <remarks>
	/// The ColumnChanging and ColumnChanged events occur when a change is made to the value 
	/// of a property of a <see cref="ClassDetails"/> object.
	/// </remarks>
	public class ClassDetailsEventArgs : System.EventArgs
	{
		private ClassDetailsColumn column;
		private object value;
		
		///<summary>
		/// Initalizes a new Instance of the ClassDetailsEventArgs class.
		///</summary>
		public ClassDetailsEventArgs(ClassDetailsColumn column)
		{
			this.column = column;
		}
		
		///<summary>
		/// Initalizes a new Instance of the ClassDetailsEventArgs class.
		///</summary>
		public ClassDetailsEventArgs(ClassDetailsColumn column, object value)
		{
			this.column = column;
			this.value = value;
		}
		
		///<summary>
		/// The ClassDetailsColumn that was modified, which has raised the event.
		///</summary>
		///<value cref="ClassDetailsColumn" />
		public ClassDetailsColumn Column { get { return this.column; } }
		
		/// <summary>
        /// Gets the current value of the column.
        /// </summary>
        /// <value>The current value of the column.</value>
		public object Value{ get { return this.value; } }

	}
	#endregion
	
	///<summary>
	/// Define a delegate for all ClassDetails related events.
	///</summary>
	public delegate void ClassDetailsEventHandler(object sender, ClassDetailsEventArgs e);
	
	#region ClassDetailsComparer
		
	/// <summary>
	///	Strongly Typed IComparer
	/// </summary>
	public class ClassDetailsComparer : System.Collections.Generic.IComparer<ClassDetails>
	{
		ClassDetailsColumn whichComparison;
		
		/// <summary>
        /// Initializes a new instance of the <see cref="T:ClassDetailsComparer"/> class.
        /// </summary>
		public ClassDetailsComparer()
        {            
        }               
        
        /// <summary>
        /// Initializes a new instance of the <see cref="T:ClassDetailsComparer"/> class.
        /// </summary>
        /// <param name="column">The column to sort on.</param>
        public ClassDetailsComparer(ClassDetailsColumn column)
        {
            this.whichComparison = column;
        }

		/// <summary>
        /// Determines whether the specified <c cref="ClassDetails"/> instances are considered equal.
        /// </summary>
        /// <param name="a">The first <c cref="ClassDetails"/> to compare.</param>
        /// <param name="b">The second <c>ClassDetails</c> to compare.</param>
        /// <returns>true if objA is the same instance as objB or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
        public bool Equals(ClassDetails a, ClassDetails b)
        {
            return this.Compare(a, b) == 0;
        }

		/// <summary>
        /// Gets the hash code of the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns></returns>
        public int GetHashCode(ClassDetails entity)
        {
            return entity.GetHashCode();
        }

        /// <summary>
        /// Performs a case-insensitive comparison of two objects of the same type and returns a value indicating whether one is less than, equal to, or greater than the other.
        /// </summary>
        /// <param name="a">The first object to compare.</param>
        /// <param name="b">The second object to compare.</param>
        /// <returns></returns>
        public int Compare(ClassDetails a, ClassDetails b)
        {
        	EntityPropertyComparer entityPropertyComparer = new EntityPropertyComparer(this.whichComparison.ToString());
        	return entityPropertyComparer.Compare(a, b);
        }

		/// <summary>
        /// Gets or sets the column that will be used for comparison.
        /// </summary>
        /// <value>The comparison column.</value>
        public ClassDetailsColumn WhichComparison
        {
            get { return this.whichComparison; }
            set { this.whichComparison = value; }
        }
	}
	
	#endregion
	
	#region ClassDetailsKey Class

	/// <summary>
	/// Wraps the unique identifier values for the <see cref="ClassDetails"/> object.
	/// </summary>
	[Serializable]
	[CLSCompliant(true)]
	public class ClassDetailsKey : EntityKeyBase
	{
		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the ClassDetailsKey class.
		/// </summary>
		public ClassDetailsKey()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the ClassDetailsKey class.
		/// </summary>
		public ClassDetailsKey(ClassDetailsBase entity)
		{
			this.Entity = entity;

			#region Init Properties

			if ( entity != null )
			{
				this.ClassId = entity.ClassId;
			}

			#endregion
		}
		
		/// <summary>
		/// Initializes a new instance of the ClassDetailsKey class.
		/// </summary>
		public ClassDetailsKey(System.Int32 _classId)
		{
			#region Init Properties

			this.ClassId = _classId;

			#endregion
		}
		
		#endregion Constructors

		#region Properties
		
		// member variable for the Entity property
		private ClassDetailsBase _entity;
		
		/// <summary>
		/// Gets or sets the Entity property.
		/// </summary>
		public ClassDetailsBase Entity
		{
			get { return _entity; }
			set { _entity = value; }
		}
		
		// member variable for the ClassId property
		private System.Int32 _classId;
		
		/// <summary>
		/// Gets or sets the ClassId property.
		/// </summary>
		public System.Int32 ClassId
		{
			get { return _classId; }
			set
			{
				if ( this.Entity != null )
					this.Entity.ClassId = value;
				
				_classId = value;
			}
		}
		
		#endregion

		#region Methods
		
		/// <summary>
		/// Reads values from the supplied <see cref="IDictionary"/> object into
		/// properties of the current object.
		/// </summary>
		/// <param name="values">An <see cref="IDictionary"/> instance that contains
		/// the key/value pairs to be used as property values.</param>
		public override void Load(IDictionary values)
		{
			#region Init Properties

			if ( values != null )
			{
				ClassId = ( values["ClassId"] != null ) ? (System.Int32) EntityUtil.ChangeType(values["ClassId"], typeof(System.Int32)) : (int)0;
			}

			#endregion
		}

		/// <summary>
		/// Creates a new <see cref="IDictionary"/> object and populates it
		/// with the property values of the current object.
		/// </summary>
		/// <returns>A collection of name/value pairs.</returns>
		public override IDictionary ToDictionary()
		{
			IDictionary values = new Hashtable();

			#region Init Dictionary

			values.Add("ClassId", ClassId);

			#endregion Init Dictionary

			return values;
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return String.Format("ClassId: {0}{1}",
								ClassId,
								System.Environment.NewLine);
		}

		#endregion Methods
	}
	
	#endregion	

	#region ClassDetailsColumn Enum
	
	/// <summary>
	/// Enumerate the ClassDetails columns.
	/// </summary>
	[Serializable]
	public enum ClassDetailsColumn : int
	{
		/// <summary>
		/// ClassId : 
		/// </summary>
		[EnumTextValue("ClassId")]
		[ColumnEnum("ClassId", typeof(System.Int32), System.Data.DbType.Int32, true, false, false)]
		ClassId = 1,
		/// <summary>
		/// ClassName : 
		/// </summary>
		[EnumTextValue("ClassName")]
		[ColumnEnum("ClassName", typeof(System.String), System.Data.DbType.String, false, false, true, 50)]
		ClassName = 2,
		/// <summary>
		/// ClassTime : 
		/// </summary>
		[EnumTextValue("ClassTime")]
		[ColumnEnum("ClassTime", typeof(System.Int32), System.Data.DbType.Int32, false, false, true)]
		ClassTime = 3,
		/// <summary>
		/// CourseId : 
		/// </summary>
		[EnumTextValue("CourseId")]
		[ColumnEnum("CourseId", typeof(System.Int32), System.Data.DbType.Int32, false, false, true)]
		CourseId = 4,
		/// <summary>
		/// TeacherId : 
		/// </summary>
		[EnumTextValue("TeacherId")]
		[ColumnEnum("TeacherId", typeof(System.Int32), System.Data.DbType.Int32, false, false, true)]
		TeacherId = 5
	}//End enum

	#endregion ClassDetailsColumn Enum

} // end namespace
