
/*
	File generated by NetTiers templates [www.nettiers.com]
	Important: Do not modify this file. Edit the file CourseCertificate.cs instead.
*/

#region using directives
using System;
using System.ComponentModel;
using System.Collections;
using System.Xml.Serialization;
using System.Runtime.Serialization;

using AIProject.Entities.Validation;
#endregion

namespace AIProject.Entities
{
	///<summary>
	/// An object representation of the 'CourseCertificate' table. [No description found the database]	
	///</summary>
	[Serializable]
	[DataObject, CLSCompliant(true)]
	public abstract partial class CourseCertificateBase : EntityBase, ICourseCertificate, IEntityId<CourseCertificateKey>, System.IComparable, System.ICloneable, ICloneableEx, IEditableObject, IComponent, INotifyPropertyChanged
	{		
		#region Variable Declarations
		
		/// <summary>
		///  Hold the inner data of the entity.
		/// </summary>
		private CourseCertificateEntityData entityData;
		
		/// <summary>
		/// 	Hold the original data of the entity, as loaded from the repository.
		/// </summary>
		private CourseCertificateEntityData _originalData;
		
		/// <summary>
		/// 	Hold a backup of the inner data of the entity.
		/// </summary>
		private CourseCertificateEntityData backupData; 
		
		/// <summary>
		/// 	Key used if Tracking is Enabled for the <see cref="EntityLocator" />.
		/// </summary>
		private string entityTrackingKey;
		
		/// <summary>
		/// 	Hold the parent TList&lt;entity&gt; in which this entity maybe contained.
		/// </summary>
		/// <remark>Mostly used for databinding</remark>
		[NonSerialized]
		private TList<CourseCertificate> parentCollection;
		
		private bool inTxn = false;
		
		/// <summary>
		/// Occurs when a value is being changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event CourseCertificateEventHandler ColumnChanging;		
		
		/// <summary>
		/// Occurs after a value has been changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event CourseCertificateEventHandler ColumnChanged;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="CourseCertificateBase"/> instance.
		///</summary>
		public CourseCertificateBase()
		{
			this.entityData = new CourseCertificateEntityData();
			this.backupData = null;
		}		
		
		///<summary>
		/// Creates a new <see cref="CourseCertificateBase"/> instance.
		///</summary>
		///<param name="_certificateName"></param>
		///<param name="_description"></param>
		public CourseCertificateBase(System.String _certificateName, System.String _description)
		{
			this.entityData = new CourseCertificateEntityData();
			this.backupData = null;

			this.CertificateName = _certificateName;
			this.Description = _description;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="CourseCertificate"/> instance.
		///</summary>
		///<param name="_certificateName"></param>
		///<param name="_description"></param>
		public static CourseCertificate CreateCourseCertificate(System.String _certificateName, System.String _description)
		{
			CourseCertificate newCourseCertificate = new CourseCertificate();
			newCourseCertificate.CertificateName = _certificateName;
			newCourseCertificate.Description = _description;
			return newCourseCertificate;
		}
				
		#endregion Constructors
			
		#region Properties	
		
		#region Data Properties		
		/// <summary>
		/// 	Gets or sets the CertificateId property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>




		[ReadOnlyAttribute(false)/*, XmlIgnoreAttribute()*/, DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, true, false)]
		public virtual System.Int32 CertificateId
		{
			get
			{
				return this.entityData.CertificateId; 
			}
			
			set
			{
				if (this.entityData.CertificateId == value)
					return;
					
				OnColumnChanging(CourseCertificateColumn.CertificateId, this.entityData.CertificateId);
				this.entityData.CertificateId = value;
				this.EntityId.CertificateId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(CourseCertificateColumn.CertificateId, this.entityData.CertificateId);
				OnPropertyChanged("CertificateId");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the CertificateName property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 50)]
		public virtual System.String CertificateName
		{
			get
			{
				return this.entityData.CertificateName; 
			}
			
			set
			{
				if (this.entityData.CertificateName == value)
					return;
					
				OnColumnChanging(CourseCertificateColumn.CertificateName, this.entityData.CertificateName);
				this.entityData.CertificateName = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(CourseCertificateColumn.CertificateName, this.entityData.CertificateName);
				OnPropertyChanged("CertificateName");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Description property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 1024)]
		public virtual System.String Description
		{
			get
			{
				return this.entityData.Description; 
			}
			
			set
			{
				if (this.entityData.Description == value)
					return;
					
				OnColumnChanging(CourseCertificateColumn.Description, this.entityData.Description);
				this.entityData.Description = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(CourseCertificateColumn.Description, this.entityData.Description);
				OnPropertyChanged("Description");
			}
		}
		
		#endregion Data Properties		

		#region Source Foreign Key Property
				
		#endregion
		
		#region Children Collections
	
		/// <summary>
		///	Holds a collection of CourseDetails objects
		///	which are related to this object through the relation FK_CourseDetails_CourseCertificate
		/// </summary>	
		[System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual TList<CourseDetails> CourseDetailsCollection
		{
			get { return entityData.CourseDetailsCollection; }
			set { entityData.CourseDetailsCollection = value; }	
		}
		#endregion Children Collections
		
		#endregion
		#region Validation
		
		/// <summary>
		/// Assigns validation rules to this object based on model definition.
		/// </summary>
		/// <remarks>This method overrides the base class to add schema related validation.</remarks>
		protected override void AddValidationRules()
		{
			//Validation rules based on database schema.
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("CertificateName", "Certificate Name", 50));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("Description", "Description", 1024));
		}
   		#endregion
		
		#region Table Meta Data
		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string TableName
		{
			get { return "CourseCertificate"; }
		}
		
		/// <summary>
		///		The name of the underlying database table's columns.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string[] TableColumns
		{
			get
			{
				return new string[] {"CertificateId", "CertificateName", "Description"};
			}
		}
		#endregion 
		
		#region IEditableObject
		
		#region  CancelAddNew Event
		/// <summary>
        /// The delegate for the CancelAddNew event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		public delegate void CancelAddNewEventHandler(object sender, EventArgs e);
    
    	/// <summary>
		/// The CancelAddNew event.
		/// </summary>
		[field:NonSerialized]
		public event CancelAddNewEventHandler CancelAddNew ;

		/// <summary>
        /// Called when [cancel add new].
        /// </summary>
        public void OnCancelAddNew()
        {    
			if (!SuppressEntityEvents)
			{
	            CancelAddNewEventHandler handler = CancelAddNew ;
            	if (handler != null)
	            {    
    	            handler(this, EventArgs.Empty) ;
        	    }
	        }
        }
		#endregion 
		
		/// <summary>
		/// Begins an edit on an object.
		/// </summary>
		void IEditableObject.BeginEdit() 
	    {
	        //Console.WriteLine("Start BeginEdit");
	        if (!inTxn) 
	        {
	            this.backupData = this.entityData.Clone() as CourseCertificateEntityData;
	            inTxn = true;
	            //Console.WriteLine("BeginEdit");
	        }
	        //Console.WriteLine("End BeginEdit");
	    }
	
		/// <summary>
		/// Discards changes since the last <c>BeginEdit</c> call.
		/// </summary>
	    void IEditableObject.CancelEdit() 
	    {
	        //Console.WriteLine("Start CancelEdit");
	        if (this.inTxn) 
	        {
	            this.entityData = this.backupData;
	            this.backupData = null;
				this.inTxn = false;

				if (this.bindingIsNew)
	        	//if (this.EntityState == EntityState.Added)
	        	{
					if (this.parentCollection != null)
						this.parentCollection.Remove( (CourseCertificate) this ) ;
				}	            
	        }
	        //Console.WriteLine("End CancelEdit");
	    }
	
		/// <summary>
		/// Pushes changes since the last <c>BeginEdit</c> or <c>IBindingList.AddNew</c> call into the underlying object.
		/// </summary>
	    void IEditableObject.EndEdit() 
	    {
	        //Console.WriteLine("Start EndEdit" + this.custData.id + this.custData.lastName);
	        if (this.inTxn) 
	        {
	            this.backupData = null;
				if (this.IsDirty) 
				{
					if (this.bindingIsNew) {
						this.EntityState = EntityState.Added;
						this.bindingIsNew = false ;
					}
					else
						if (this.EntityState == EntityState.Unchanged) 
							this.EntityState = EntityState.Changed ;
				}

				this.bindingIsNew = false ;
	            this.inTxn = false;	            
	        }
	        //Console.WriteLine("End EndEdit");
	    }
	    
	    /// <summary>
        /// Gets or sets the parent collection of this current entity, if available.
        /// </summary>
        /// <value>The parent collection.</value>
	    [XmlIgnore]
		[Browsable(false)]
	    public override object ParentCollection
	    {
	        get 
	        {
	            return this.parentCollection;
	        }
	        set 
	        {
	            this.parentCollection = value as TList<CourseCertificate>;
	        }
	    }
	    
	    /// <summary>
        /// Called when the entity is changed.
        /// </summary>
	    private void OnEntityChanged() 
	    {
	        if (!SuppressEntityEvents && !inTxn && this.parentCollection != null) 
	        {
	            this.parentCollection.EntityChanged(this as CourseCertificate);
	        }
	    }


		#endregion
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed CourseCertificate Entity 
		///</summary>
		protected virtual CourseCertificate Copy(IDictionary existingCopies)
		{
			if (existingCopies == null)
			{
				// This is the root of the tree to be copied!
				existingCopies = new Hashtable();
			}

			//shallow copy entity
			CourseCertificate copy = new CourseCertificate();
			existingCopies.Add(this, copy);
			copy.SuppressEntityEvents = true;
				copy.CertificateId = this.CertificateId;
				copy.CertificateName = this.CertificateName;
				copy.Description = this.Description;
			
		
			//deep copy nested objects
			copy.CourseDetailsCollection = (TList<CourseDetails>) MakeCopyOf(this.CourseDetailsCollection, existingCopies); 
			copy.EntityState = this.EntityState;
			copy.SuppressEntityEvents = false;
			return copy;
		}		
		
		
		
		///<summary>
		///  Returns a Typed CourseCertificate Entity 
		///</summary>
		public virtual CourseCertificate Copy()
		{
			return this.Copy(null);	
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone()
		{
			return this.Copy(null);
		}
		
		///<summary>
		/// ICloneableEx.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone(IDictionary existingCopies)
		{
			return this.Copy(existingCopies);
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x == null)
				return null;
				
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x, IDictionary existingCopies)
		{
			if (x == null)
				return null;
			
			if (x is ICloneableEx)
			{
				// Return a deep copy of the object
				return ((ICloneableEx)x).Clone(existingCopies);
			}
			else if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable or IClonableEx Interface.");
		}
		
		
		///<summary>
		///  Returns a Typed CourseCertificate Entity which is a deep copy of the current entity.
		///</summary>
		public virtual CourseCertificate DeepCopy()
		{
			return EntityHelper.Clone<CourseCertificate>(this as CourseCertificate);	
		}
		#endregion
		
		#region Methods	
			
		///<summary>
		/// Revert all changes and restore original values.
		///</summary>
		public override void CancelChanges()
		{
			IEditableObject obj = (IEditableObject) this;
			obj.CancelEdit();

			this.entityData = null;
			if (this._originalData != null)
			{
				this.entityData = this._originalData.Clone() as CourseCertificateEntityData;
			}
			else
			{
				//Since this had no _originalData, then just reset the entityData with a new one.  entityData cannot be null.
				this.entityData = new CourseCertificateEntityData();
			}
		}	
		
		/// <summary>
		/// Accepts the changes made to this object.
		/// </summary>
		/// <remarks>
		/// After calling this method, properties: IsDirty, IsNew are false. IsDeleted flag remains unchanged as it is handled by the parent List.
		/// </remarks>
		public override void AcceptChanges()
		{
			base.AcceptChanges();

			// we keep of the original version of the data
			this._originalData = null;
			this._originalData = this.entityData.Clone() as CourseCertificateEntityData;
		}
		
		#region Comparision with original data
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="column">The column.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool IsPropertyChanged(CourseCertificateColumn column)
		{
			switch(column)
			{
					case CourseCertificateColumn.CertificateId:
					return entityData.CertificateId != _originalData.CertificateId;
					case CourseCertificateColumn.CertificateName:
					return entityData.CertificateName != _originalData.CertificateName;
					case CourseCertificateColumn.Description:
					return entityData.Description != _originalData.Description;
			
				default:
					return false;
			}
		}
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="columnName">The column name.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public override bool IsPropertyChanged(string columnName)
		{
			return 	IsPropertyChanged(EntityHelper.GetEnumValue< CourseCertificateColumn >(columnName));
		}
		
		/// <summary>
		/// Determines whether the data has changed from original.
		/// </summary>
		/// <returns>
		/// 	<c>true</c> if data has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool HasDataChanged()
		{
			bool result = false;
			result = result || entityData.CertificateId != _originalData.CertificateId;
			result = result || entityData.CertificateName != _originalData.CertificateName;
			result = result || entityData.Description != _originalData.Description;
			return result;
		}	
		
		///<summary>
		///  Returns a CourseCertificate Entity with the original data.
		///</summary>
		public CourseCertificate GetOriginalEntity()
		{
			if (_originalData != null)
				return CreateCourseCertificate(
				_originalData.CertificateName,
				_originalData.Description
				);
				
			return (CourseCertificate)this.Clone();
		}
		#endregion
	
	#region Value Semantics Instance Equality
        ///<summary>
        /// Returns a value indicating whether this instance is equal to a specified object using value semantics.
        ///</summary>
        ///<param name="Object1">An object to compare to this instance.</param>
        ///<returns>true if Object1 is a <see cref="CourseCertificateBase"/> and has the same value as this instance; otherwise, false.</returns>
        public override bool Equals(object Object1)
        {
			// Cast exception if Object1 is null or DbNull
			if (Object1 != null && Object1 != DBNull.Value && Object1 is CourseCertificateBase)
				return ValueEquals(this, (CourseCertificateBase)Object1);
			else
				return false;
        }

        /// <summary>
		/// Serves as a hash function for a particular type, suitable for use in hashing algorithms and data structures like a hash table.
        /// Provides a hash function that is appropriate for <see cref="CourseCertificateBase"/> class 
        /// and that ensures a better distribution in the hash table
        /// </summary>
        /// <returns>number (hash code) that corresponds to the value of an object</returns>
        public override int GetHashCode()
        {
			return this.CertificateId.GetHashCode() ^ 
					((this.CertificateName == null) ? string.Empty : this.CertificateName.ToString()).GetHashCode() ^ 
					((this.Description == null) ? string.Empty : this.Description.ToString()).GetHashCode();
        }
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object using value semantics.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="CourseCertificateBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(CourseCertificateBase toObject)
		{
			if (toObject == null)
				return false;
			return ValueEquals(this, toObject);
		}
		#endregion
		
		///<summary>
		/// Determines whether the specified <see cref="CourseCertificateBase"/> instances are considered equal using value semantics.
		///</summary>
		///<param name="Object1">The first <see cref="CourseCertificateBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="CourseCertificateBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool ValueEquals(CourseCertificateBase Object1, CourseCertificateBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;
				
			bool equal = true;
			if (Object1.CertificateId != Object2.CertificateId)
				equal = false;
			if ( Object1.CertificateName != null && Object2.CertificateName != null )
			{
				if (Object1.CertificateName != Object2.CertificateName)
					equal = false;
			}
			else if (Object1.CertificateName == null ^ Object2.CertificateName == null )
			{
				equal = false;
			}
			if ( Object1.Description != null && Object2.Description != null )
			{
				if (Object1.Description != Object2.Description)
					equal = false;
			}
			else if (Object1.Description == null ^ Object2.Description == null )
			{
				equal = false;
			}
					
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
			//return this. GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]) .CompareTo(((CourseCertificateBase)obj).GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]));
		}
		
		/*
		// static method to get a Comparer object
        public static CourseCertificateComparer GetComparer()
        {
            return new CourseCertificateComparer();
        }
        */

        // Comparer delegates back to CourseCertificate
        // Employee uses the integer's default
        // CompareTo method
        /*
        public int CompareTo(Item rhs)
        {
            return this.Id.CompareTo(rhs.Id);
        }
        */

/*
        // Special implementation to be called by custom comparer
        public int CompareTo(CourseCertificate rhs, CourseCertificateColumn which)
        {
            switch (which)
            {
            	
            	
            	case CourseCertificateColumn.CertificateId:
            		return this.CertificateId.CompareTo(rhs.CertificateId);
            		
            		                 
            	
            	
            	case CourseCertificateColumn.CertificateName:
            		return this.CertificateName.CompareTo(rhs.CertificateName);
            		
            		                 
            	
            	
            	case CourseCertificateColumn.Description:
            		return this.Description.CompareTo(rhs.Description);
            		
            		                 
            }
            return 0;
        }
        */
	
		#endregion
		
		#region IComponent Members
		
		private ISite _site = null;

		/// <summary>
		/// Gets or Sets the site where this data is located.
		/// </summary>
		[XmlIgnore]
		[SoapIgnore]
		[Browsable(false)]
		public ISite Site
		{
			get{ return this._site; }
			set{ this._site = value; }
		}

		#endregion

		#region IDisposable Members
		
		/// <summary>
		/// Notify those that care when we dispose.
		/// </summary>
		[field:NonSerialized]
		public event System.EventHandler Disposed;

		/// <summary>
		/// Clean up. Nothing here though.
		/// </summary>
		public virtual void Dispose()
		{
			this.parentCollection = null;
			this.Dispose(true);
			GC.SuppressFinalize(this);
		}
		
		/// <summary>
		/// Clean up.
		/// </summary>
		protected virtual void Dispose(bool disposing)
		{
			if (disposing)
			{
				EventHandler handler = Disposed;
				if (handler != null)
					handler(this, EventArgs.Empty);
			}
		}
		
		#endregion
				
		#region IEntityKey<CourseCertificateKey> Members
		
		// member variable for the EntityId property
		private CourseCertificateKey _entityId;

		/// <summary>
		/// Gets or sets the EntityId property.
		/// </summary>
		[XmlIgnore]
		public virtual CourseCertificateKey EntityId
		{
			get
			{
				if ( _entityId == null )
				{
					_entityId = new CourseCertificateKey(this);
				}

				return _entityId;
			}
			set
			{
				if ( value != null )
				{
					value.Entity = this;
				}
				
				_entityId = value;
			}
		}
		
		#endregion
		
		#region EntityState
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false) , XmlIgnoreAttribute()]
		public override EntityState EntityState 
		{ 
			get{ return entityData.EntityState;	 } 
			set{ entityData.EntityState = value; } 
		}
		#endregion 
		
		#region EntityTrackingKey
		///<summary>
		/// Provides the tracking key for the <see cref="EntityLocator"/>
		///</summary>
		[XmlIgnore]
		public override string EntityTrackingKey
		{
			get
			{
				if(entityTrackingKey == null)
					entityTrackingKey = new System.Text.StringBuilder("CourseCertificate")
					.Append("|").Append( this.CertificateId.ToString()).ToString();
				return entityTrackingKey;
			}
			set
		    {
		        if (value != null)
                    entityTrackingKey = value;
		    }
		}
		#endregion 
		
		#region ToString Method
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{4}{3}- CertificateId: {0}{3}- CertificateName: {1}{3}- Description: {2}{3}{5}", 
				this.CertificateId,
				(this.CertificateName == null) ? string.Empty : this.CertificateName.ToString(),
				(this.Description == null) ? string.Empty : this.Description.ToString(),
				System.Environment.NewLine, 
				this.GetType(),
				this.Error.Length == 0 ? string.Empty : string.Format("- Error: {0}\n",this.Error));
		}
		
		#endregion ToString Method
		
		#region Inner data class
		
	/// <summary>
	///		The data structure representation of the 'CourseCertificate' table.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Serializable]
	internal protected class CourseCertificateEntityData : ICloneable, ICloneableEx
	{
		#region Variable Declarations
		private EntityState currentEntityState = EntityState.Added;
		
		#region Primary key(s)
		/// <summary>			
		/// CertificateId : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "CourseCertificate"</remarks>
		public System.Int32 CertificateId;
			
		#endregion
		
		#region Non Primary key(s)
		
		
		/// <summary>
		/// CertificateName : 
		/// </summary>
		public System.String		  CertificateName = null;
		
		/// <summary>
		/// Description : 
		/// </summary>
		public System.String		  Description = null;
		#endregion
			
		#region Source Foreign Key Property
				
		#endregion
		#endregion Variable Declarations
	
		#region Data Properties

		#region CourseDetailsCollection
		
		private TList<CourseDetails> _courseDetailsCourseCertificate;
		
		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation _courseDetailsCourseCertificate
		/// </summary>
		
		public TList<CourseDetails> CourseDetailsCollection
		{
			get
			{
				if (_courseDetailsCourseCertificate == null)
				{
				_courseDetailsCourseCertificate = new TList<CourseDetails>();
				}
	
				return _courseDetailsCourseCertificate;
			}
			set { _courseDetailsCourseCertificate = value; }
		}
		
		#endregion

		#endregion Data Properties
		
		#region Clone Method

		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public Object Clone()
		{
			CourseCertificateEntityData _tmp = new CourseCertificateEntityData();
						
			_tmp.CertificateId = this.CertificateId;
			
			_tmp.CertificateName = this.CertificateName;
			_tmp.Description = this.Description;
			
			#region Source Parent Composite Entities
			#endregion
		
			#region Child Collections
			//deep copy nested objects
			if (this._courseDetailsCourseCertificate != null)
				_tmp.CourseDetailsCollection = (TList<CourseDetails>) MakeCopyOf(this.CourseDetailsCollection); 
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public object Clone(IDictionary existingCopies)
		{
			if (existingCopies == null)
				existingCopies = new Hashtable();
				
			CourseCertificateEntityData _tmp = new CourseCertificateEntityData();
						
			_tmp.CertificateId = this.CertificateId;
			
			_tmp.CertificateName = this.CertificateName;
			_tmp.Description = this.Description;
			
			#region Source Parent Composite Entities
			#endregion
		
			#region Child Collections
			//deep copy nested objects
			_tmp.CourseDetailsCollection = (TList<CourseDetails>) MakeCopyOf(this.CourseDetailsCollection, existingCopies); 
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		#endregion Clone Method
		
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public EntityState	EntityState
		{
			get { return currentEntityState;  }
			set { currentEntityState = value; }
		}
	
	}//End struct











		#endregion
		
				
		
		#region Events trigger
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="CourseCertificateColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanging(CourseCertificateColumn column)
		{
			OnColumnChanging(column, null);
			return;
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="CourseCertificateColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanged(CourseCertificateColumn column)
		{
			OnColumnChanged(column, null);
			return;
		} 
		
		
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="CourseCertificateColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanging(CourseCertificateColumn column, object value)
		{
			if(IsEntityTracked && EntityState != EntityState.Added && !EntityManager.TrackChangedEntities)
				EntityManager.StopTracking(entityTrackingKey);
				
			if (!SuppressEntityEvents)
			{
				CourseCertificateEventHandler handler = ColumnChanging;
				if(handler != null)
				{
					handler(this, new CourseCertificateEventArgs(column, value));
				}
			}
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="CourseCertificateColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanged(CourseCertificateColumn column, object value)
		{
			if (!SuppressEntityEvents)
			{
				CourseCertificateEventHandler handler = ColumnChanged;
				if(handler != null)
				{
					handler(this, new CourseCertificateEventArgs(column, value));
				}
			
				// warn the parent list that i have changed
				OnEntityChanged();
			}
		} 
		#endregion
			
	} // End Class
	
	
	#region CourseCertificateEventArgs class
	/// <summary>
	/// Provides data for the ColumnChanging and ColumnChanged events.
	/// </summary>
	/// <remarks>
	/// The ColumnChanging and ColumnChanged events occur when a change is made to the value 
	/// of a property of a <see cref="CourseCertificate"/> object.
	/// </remarks>
	public class CourseCertificateEventArgs : System.EventArgs
	{
		private CourseCertificateColumn column;
		private object value;
		
		///<summary>
		/// Initalizes a new Instance of the CourseCertificateEventArgs class.
		///</summary>
		public CourseCertificateEventArgs(CourseCertificateColumn column)
		{
			this.column = column;
		}
		
		///<summary>
		/// Initalizes a new Instance of the CourseCertificateEventArgs class.
		///</summary>
		public CourseCertificateEventArgs(CourseCertificateColumn column, object value)
		{
			this.column = column;
			this.value = value;
		}
		
		///<summary>
		/// The CourseCertificateColumn that was modified, which has raised the event.
		///</summary>
		///<value cref="CourseCertificateColumn" />
		public CourseCertificateColumn Column { get { return this.column; } }
		
		/// <summary>
        /// Gets the current value of the column.
        /// </summary>
        /// <value>The current value of the column.</value>
		public object Value{ get { return this.value; } }

	}
	#endregion
	
	///<summary>
	/// Define a delegate for all CourseCertificate related events.
	///</summary>
	public delegate void CourseCertificateEventHandler(object sender, CourseCertificateEventArgs e);
	
	#region CourseCertificateComparer
		
	/// <summary>
	///	Strongly Typed IComparer
	/// </summary>
	public class CourseCertificateComparer : System.Collections.Generic.IComparer<CourseCertificate>
	{
		CourseCertificateColumn whichComparison;
		
		/// <summary>
        /// Initializes a new instance of the <see cref="T:CourseCertificateComparer"/> class.
        /// </summary>
		public CourseCertificateComparer()
        {            
        }               
        
        /// <summary>
        /// Initializes a new instance of the <see cref="T:CourseCertificateComparer"/> class.
        /// </summary>
        /// <param name="column">The column to sort on.</param>
        public CourseCertificateComparer(CourseCertificateColumn column)
        {
            this.whichComparison = column;
        }

		/// <summary>
        /// Determines whether the specified <c cref="CourseCertificate"/> instances are considered equal.
        /// </summary>
        /// <param name="a">The first <c cref="CourseCertificate"/> to compare.</param>
        /// <param name="b">The second <c>CourseCertificate</c> to compare.</param>
        /// <returns>true if objA is the same instance as objB or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
        public bool Equals(CourseCertificate a, CourseCertificate b)
        {
            return this.Compare(a, b) == 0;
        }

		/// <summary>
        /// Gets the hash code of the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns></returns>
        public int GetHashCode(CourseCertificate entity)
        {
            return entity.GetHashCode();
        }

        /// <summary>
        /// Performs a case-insensitive comparison of two objects of the same type and returns a value indicating whether one is less than, equal to, or greater than the other.
        /// </summary>
        /// <param name="a">The first object to compare.</param>
        /// <param name="b">The second object to compare.</param>
        /// <returns></returns>
        public int Compare(CourseCertificate a, CourseCertificate b)
        {
        	EntityPropertyComparer entityPropertyComparer = new EntityPropertyComparer(this.whichComparison.ToString());
        	return entityPropertyComparer.Compare(a, b);
        }

		/// <summary>
        /// Gets or sets the column that will be used for comparison.
        /// </summary>
        /// <value>The comparison column.</value>
        public CourseCertificateColumn WhichComparison
        {
            get { return this.whichComparison; }
            set { this.whichComparison = value; }
        }
	}
	
	#endregion
	
	#region CourseCertificateKey Class

	/// <summary>
	/// Wraps the unique identifier values for the <see cref="CourseCertificate"/> object.
	/// </summary>
	[Serializable]
	[CLSCompliant(true)]
	public class CourseCertificateKey : EntityKeyBase
	{
		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the CourseCertificateKey class.
		/// </summary>
		public CourseCertificateKey()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the CourseCertificateKey class.
		/// </summary>
		public CourseCertificateKey(CourseCertificateBase entity)
		{
			this.Entity = entity;

			#region Init Properties

			if ( entity != null )
			{
				this.CertificateId = entity.CertificateId;
			}

			#endregion
		}
		
		/// <summary>
		/// Initializes a new instance of the CourseCertificateKey class.
		/// </summary>
		public CourseCertificateKey(System.Int32 _certificateId)
		{
			#region Init Properties

			this.CertificateId = _certificateId;

			#endregion
		}
		
		#endregion Constructors

		#region Properties
		
		// member variable for the Entity property
		private CourseCertificateBase _entity;
		
		/// <summary>
		/// Gets or sets the Entity property.
		/// </summary>
		public CourseCertificateBase Entity
		{
			get { return _entity; }
			set { _entity = value; }
		}
		
		// member variable for the CertificateId property
		private System.Int32 _certificateId;
		
		/// <summary>
		/// Gets or sets the CertificateId property.
		/// </summary>
		public System.Int32 CertificateId
		{
			get { return _certificateId; }
			set
			{
				if ( this.Entity != null )
					this.Entity.CertificateId = value;
				
				_certificateId = value;
			}
		}
		
		#endregion

		#region Methods
		
		/// <summary>
		/// Reads values from the supplied <see cref="IDictionary"/> object into
		/// properties of the current object.
		/// </summary>
		/// <param name="values">An <see cref="IDictionary"/> instance that contains
		/// the key/value pairs to be used as property values.</param>
		public override void Load(IDictionary values)
		{
			#region Init Properties

			if ( values != null )
			{
				CertificateId = ( values["CertificateId"] != null ) ? (System.Int32) EntityUtil.ChangeType(values["CertificateId"], typeof(System.Int32)) : (int)0;
			}

			#endregion
		}

		/// <summary>
		/// Creates a new <see cref="IDictionary"/> object and populates it
		/// with the property values of the current object.
		/// </summary>
		/// <returns>A collection of name/value pairs.</returns>
		public override IDictionary ToDictionary()
		{
			IDictionary values = new Hashtable();

			#region Init Dictionary

			values.Add("CertificateId", CertificateId);

			#endregion Init Dictionary

			return values;
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return String.Format("CertificateId: {0}{1}",
								CertificateId,
								System.Environment.NewLine);
		}

		#endregion Methods
	}
	
	#endregion	

	#region CourseCertificateColumn Enum
	
	/// <summary>
	/// Enumerate the CourseCertificate columns.
	/// </summary>
	[Serializable]
	public enum CourseCertificateColumn : int
	{
		/// <summary>
		/// CertificateId : 
		/// </summary>
		[EnumTextValue("CertificateId")]
		[ColumnEnum("CertificateId", typeof(System.Int32), System.Data.DbType.Int32, true, true, false)]
		CertificateId = 1,
		/// <summary>
		/// CertificateName : 
		/// </summary>
		[EnumTextValue("CertificateName")]
		[ColumnEnum("CertificateName", typeof(System.String), System.Data.DbType.String, false, false, true, 50)]
		CertificateName = 2,
		/// <summary>
		/// Description : 
		/// </summary>
		[EnumTextValue("Description")]
		[ColumnEnum("Description", typeof(System.String), System.Data.DbType.String, false, false, true, 1024)]
		Description = 3
	}//End enum

	#endregion CourseCertificateColumn Enum

} // end namespace
